
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Asceticism` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Asceticism
 * 
 */
export type AsceticismModel = runtime.Types.Result.DefaultSelection<Prisma.$AsceticismPayload>

export type AggregateAsceticism = {
  _count: AsceticismCountAggregateOutputType | null
  _avg: AsceticismAvgAggregateOutputType | null
  _sum: AsceticismSumAggregateOutputType | null
  _min: AsceticismMinAggregateOutputType | null
  _max: AsceticismMaxAggregateOutputType | null
}

export type AsceticismAvgAggregateOutputType = {
  id: number | null
  creatorId: number | null
}

export type AsceticismSumAggregateOutputType = {
  id: number | null
  creatorId: number | null
}

export type AsceticismMinAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  category: string | null
  icon: string | null
  isTemplate: boolean | null
  creatorId: number | null
  type: $Enums.TrackingType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AsceticismMaxAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  category: string | null
  icon: string | null
  isTemplate: boolean | null
  creatorId: number | null
  type: $Enums.TrackingType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AsceticismCountAggregateOutputType = {
  id: number
  title: number
  description: number
  category: number
  icon: number
  isTemplate: number
  creatorId: number
  type: number
  metadata: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AsceticismAvgAggregateInputType = {
  id?: true
  creatorId?: true
}

export type AsceticismSumAggregateInputType = {
  id?: true
  creatorId?: true
}

export type AsceticismMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  icon?: true
  isTemplate?: true
  creatorId?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type AsceticismMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  icon?: true
  isTemplate?: true
  creatorId?: true
  type?: true
  createdAt?: true
  updatedAt?: true
}

export type AsceticismCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  category?: true
  icon?: true
  isTemplate?: true
  creatorId?: true
  type?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AsceticismAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Asceticism to aggregate.
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Asceticisms to fetch.
   */
  orderBy?: Prisma.AsceticismOrderByWithRelationInput | Prisma.AsceticismOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AsceticismWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Asceticisms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Asceticisms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Asceticisms
  **/
  _count?: true | AsceticismCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AsceticismAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AsceticismSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AsceticismMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AsceticismMaxAggregateInputType
}

export type GetAsceticismAggregateType<T extends AsceticismAggregateArgs> = {
      [P in keyof T & keyof AggregateAsceticism]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAsceticism[P]>
    : Prisma.GetScalarType<T[P], AggregateAsceticism[P]>
}




export type AsceticismGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AsceticismWhereInput
  orderBy?: Prisma.AsceticismOrderByWithAggregationInput | Prisma.AsceticismOrderByWithAggregationInput[]
  by: Prisma.AsceticismScalarFieldEnum[] | Prisma.AsceticismScalarFieldEnum
  having?: Prisma.AsceticismScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AsceticismCountAggregateInputType | true
  _avg?: AsceticismAvgAggregateInputType
  _sum?: AsceticismSumAggregateInputType
  _min?: AsceticismMinAggregateInputType
  _max?: AsceticismMaxAggregateInputType
}

export type AsceticismGroupByOutputType = {
  id: number
  title: string
  description: string | null
  category: string
  icon: string | null
  isTemplate: boolean
  creatorId: number | null
  type: $Enums.TrackingType
  metadata: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: AsceticismCountAggregateOutputType | null
  _avg: AsceticismAvgAggregateOutputType | null
  _sum: AsceticismSumAggregateOutputType | null
  _min: AsceticismMinAggregateOutputType | null
  _max: AsceticismMaxAggregateOutputType | null
}

type GetAsceticismGroupByPayload<T extends AsceticismGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AsceticismGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AsceticismGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AsceticismGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AsceticismGroupByOutputType[P]>
      }
    >
  >



export type AsceticismWhereInput = {
  AND?: Prisma.AsceticismWhereInput | Prisma.AsceticismWhereInput[]
  OR?: Prisma.AsceticismWhereInput[]
  NOT?: Prisma.AsceticismWhereInput | Prisma.AsceticismWhereInput[]
  id?: Prisma.IntFilter<"Asceticism"> | number
  title?: Prisma.StringFilter<"Asceticism"> | string
  description?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  category?: Prisma.StringFilter<"Asceticism"> | string
  icon?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  isTemplate?: Prisma.BoolFilter<"Asceticism"> | boolean
  creatorId?: Prisma.IntNullableFilter<"Asceticism"> | number | null
  type?: Prisma.EnumTrackingTypeFilter<"Asceticism"> | $Enums.TrackingType
  metadata?: Prisma.JsonNullableFilter<"Asceticism">
  createdAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
  userAsceticisms?: Prisma.UserAsceticismListRelationFilter
  programItems?: Prisma.ProgramItemListRelationFilter
  packageItems?: Prisma.PackageItemListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type AsceticismOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  isTemplate?: Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userAsceticisms?: Prisma.UserAsceticismOrderByRelationAggregateInput
  programItems?: Prisma.ProgramItemOrderByRelationAggregateInput
  packageItems?: Prisma.PackageItemOrderByRelationAggregateInput
  creator?: Prisma.UserOrderByWithRelationInput
}

export type AsceticismWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AsceticismWhereInput | Prisma.AsceticismWhereInput[]
  OR?: Prisma.AsceticismWhereInput[]
  NOT?: Prisma.AsceticismWhereInput | Prisma.AsceticismWhereInput[]
  title?: Prisma.StringFilter<"Asceticism"> | string
  description?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  category?: Prisma.StringFilter<"Asceticism"> | string
  icon?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  isTemplate?: Prisma.BoolFilter<"Asceticism"> | boolean
  creatorId?: Prisma.IntNullableFilter<"Asceticism"> | number | null
  type?: Prisma.EnumTrackingTypeFilter<"Asceticism"> | $Enums.TrackingType
  metadata?: Prisma.JsonNullableFilter<"Asceticism">
  createdAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
  userAsceticisms?: Prisma.UserAsceticismListRelationFilter
  programItems?: Prisma.ProgramItemListRelationFilter
  packageItems?: Prisma.PackageItemListRelationFilter
  creator?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type AsceticismOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrder
  icon?: Prisma.SortOrderInput | Prisma.SortOrder
  isTemplate?: Prisma.SortOrder
  creatorId?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AsceticismCountOrderByAggregateInput
  _avg?: Prisma.AsceticismAvgOrderByAggregateInput
  _max?: Prisma.AsceticismMaxOrderByAggregateInput
  _min?: Prisma.AsceticismMinOrderByAggregateInput
  _sum?: Prisma.AsceticismSumOrderByAggregateInput
}

export type AsceticismScalarWhereWithAggregatesInput = {
  AND?: Prisma.AsceticismScalarWhereWithAggregatesInput | Prisma.AsceticismScalarWhereWithAggregatesInput[]
  OR?: Prisma.AsceticismScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AsceticismScalarWhereWithAggregatesInput | Prisma.AsceticismScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Asceticism"> | number
  title?: Prisma.StringWithAggregatesFilter<"Asceticism"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Asceticism"> | string | null
  category?: Prisma.StringWithAggregatesFilter<"Asceticism"> | string
  icon?: Prisma.StringNullableWithAggregatesFilter<"Asceticism"> | string | null
  isTemplate?: Prisma.BoolWithAggregatesFilter<"Asceticism"> | boolean
  creatorId?: Prisma.IntNullableWithAggregatesFilter<"Asceticism"> | number | null
  type?: Prisma.EnumTrackingTypeWithAggregatesFilter<"Asceticism"> | $Enums.TrackingType
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"Asceticism">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Asceticism"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Asceticism"> | Date | string
}

export type AsceticismCreateInput = {
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemCreateNestedManyWithoutAsceticismInput
  creator?: Prisma.UserCreateNestedOneWithoutCreatedAsceticismsInput
}

export type AsceticismUncheckedCreateInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  creatorId?: number | null
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemUncheckedCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemUncheckedCreateNestedManyWithoutAsceticismInput
}

export type AsceticismUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUpdateManyWithoutAsceticismNestedInput
  creator?: Prisma.UserUpdateOneWithoutCreatedAsceticismsNestedInput
}

export type AsceticismUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creatorId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUncheckedUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUncheckedUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismCreateManyInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  creatorId?: number | null
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AsceticismUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AsceticismUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creatorId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AsceticismListRelationFilter = {
  every?: Prisma.AsceticismWhereInput
  some?: Prisma.AsceticismWhereInput
  none?: Prisma.AsceticismWhereInput
}

export type AsceticismOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AsceticismCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  isTemplate?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
}

export type AsceticismMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  isTemplate?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  category?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  isTemplate?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
}

export type AsceticismScalarRelationFilter = {
  is?: Prisma.AsceticismWhereInput
  isNot?: Prisma.AsceticismWhereInput
}

export type AsceticismCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput> | Prisma.AsceticismCreateWithoutCreatorInput[] | Prisma.AsceticismUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutCreatorInput | Prisma.AsceticismCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.AsceticismCreateManyCreatorInputEnvelope
  connect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
}

export type AsceticismUncheckedCreateNestedManyWithoutCreatorInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput> | Prisma.AsceticismCreateWithoutCreatorInput[] | Prisma.AsceticismUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutCreatorInput | Prisma.AsceticismCreateOrConnectWithoutCreatorInput[]
  createMany?: Prisma.AsceticismCreateManyCreatorInputEnvelope
  connect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
}

export type AsceticismUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput> | Prisma.AsceticismCreateWithoutCreatorInput[] | Prisma.AsceticismUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutCreatorInput | Prisma.AsceticismCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.AsceticismUpsertWithWhereUniqueWithoutCreatorInput | Prisma.AsceticismUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.AsceticismCreateManyCreatorInputEnvelope
  set?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  disconnect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  delete?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  connect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  update?: Prisma.AsceticismUpdateWithWhereUniqueWithoutCreatorInput | Prisma.AsceticismUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.AsceticismUpdateManyWithWhereWithoutCreatorInput | Prisma.AsceticismUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.AsceticismScalarWhereInput | Prisma.AsceticismScalarWhereInput[]
}

export type AsceticismUncheckedUpdateManyWithoutCreatorNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput> | Prisma.AsceticismCreateWithoutCreatorInput[] | Prisma.AsceticismUncheckedCreateWithoutCreatorInput[]
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutCreatorInput | Prisma.AsceticismCreateOrConnectWithoutCreatorInput[]
  upsert?: Prisma.AsceticismUpsertWithWhereUniqueWithoutCreatorInput | Prisma.AsceticismUpsertWithWhereUniqueWithoutCreatorInput[]
  createMany?: Prisma.AsceticismCreateManyCreatorInputEnvelope
  set?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  disconnect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  delete?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  connect?: Prisma.AsceticismWhereUniqueInput | Prisma.AsceticismWhereUniqueInput[]
  update?: Prisma.AsceticismUpdateWithWhereUniqueWithoutCreatorInput | Prisma.AsceticismUpdateWithWhereUniqueWithoutCreatorInput[]
  updateMany?: Prisma.AsceticismUpdateManyWithWhereWithoutCreatorInput | Prisma.AsceticismUpdateManyWithWhereWithoutCreatorInput[]
  deleteMany?: Prisma.AsceticismScalarWhereInput | Prisma.AsceticismScalarWhereInput[]
}

export type EnumTrackingTypeFieldUpdateOperationsInput = {
  set?: $Enums.TrackingType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AsceticismCreateNestedOneWithoutUserAsceticismsInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedCreateWithoutUserAsceticismsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutUserAsceticismsInput
  connect?: Prisma.AsceticismWhereUniqueInput
}

export type AsceticismUpdateOneRequiredWithoutUserAsceticismsNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedCreateWithoutUserAsceticismsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutUserAsceticismsInput
  upsert?: Prisma.AsceticismUpsertWithoutUserAsceticismsInput
  connect?: Prisma.AsceticismWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AsceticismUpdateToOneWithWhereWithoutUserAsceticismsInput, Prisma.AsceticismUpdateWithoutUserAsceticismsInput>, Prisma.AsceticismUncheckedUpdateWithoutUserAsceticismsInput>
}

export type AsceticismCreateNestedOneWithoutPackageItemsInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutPackageItemsInput, Prisma.AsceticismUncheckedCreateWithoutPackageItemsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutPackageItemsInput
  connect?: Prisma.AsceticismWhereUniqueInput
}

export type AsceticismUpdateOneRequiredWithoutPackageItemsNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutPackageItemsInput, Prisma.AsceticismUncheckedCreateWithoutPackageItemsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutPackageItemsInput
  upsert?: Prisma.AsceticismUpsertWithoutPackageItemsInput
  connect?: Prisma.AsceticismWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AsceticismUpdateToOneWithWhereWithoutPackageItemsInput, Prisma.AsceticismUpdateWithoutPackageItemsInput>, Prisma.AsceticismUncheckedUpdateWithoutPackageItemsInput>
}

export type AsceticismCreateNestedOneWithoutProgramItemsInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutProgramItemsInput, Prisma.AsceticismUncheckedCreateWithoutProgramItemsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutProgramItemsInput
  connect?: Prisma.AsceticismWhereUniqueInput
}

export type AsceticismUpdateOneRequiredWithoutProgramItemsNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismCreateWithoutProgramItemsInput, Prisma.AsceticismUncheckedCreateWithoutProgramItemsInput>
  connectOrCreate?: Prisma.AsceticismCreateOrConnectWithoutProgramItemsInput
  upsert?: Prisma.AsceticismUpsertWithoutProgramItemsInput
  connect?: Prisma.AsceticismWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AsceticismUpdateToOneWithWhereWithoutProgramItemsInput, Prisma.AsceticismUpdateWithoutProgramItemsInput>, Prisma.AsceticismUncheckedUpdateWithoutProgramItemsInput>
}

export type AsceticismCreateWithoutCreatorInput = {
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemCreateNestedManyWithoutAsceticismInput
}

export type AsceticismUncheckedCreateWithoutCreatorInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemUncheckedCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemUncheckedCreateNestedManyWithoutAsceticismInput
}

export type AsceticismCreateOrConnectWithoutCreatorInput = {
  where: Prisma.AsceticismWhereUniqueInput
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput>
}

export type AsceticismCreateManyCreatorInputEnvelope = {
  data: Prisma.AsceticismCreateManyCreatorInput | Prisma.AsceticismCreateManyCreatorInput[]
  skipDuplicates?: boolean
}

export type AsceticismUpsertWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.AsceticismWhereUniqueInput
  update: Prisma.XOR<Prisma.AsceticismUpdateWithoutCreatorInput, Prisma.AsceticismUncheckedUpdateWithoutCreatorInput>
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutCreatorInput, Prisma.AsceticismUncheckedCreateWithoutCreatorInput>
}

export type AsceticismUpdateWithWhereUniqueWithoutCreatorInput = {
  where: Prisma.AsceticismWhereUniqueInput
  data: Prisma.XOR<Prisma.AsceticismUpdateWithoutCreatorInput, Prisma.AsceticismUncheckedUpdateWithoutCreatorInput>
}

export type AsceticismUpdateManyWithWhereWithoutCreatorInput = {
  where: Prisma.AsceticismScalarWhereInput
  data: Prisma.XOR<Prisma.AsceticismUpdateManyMutationInput, Prisma.AsceticismUncheckedUpdateManyWithoutCreatorInput>
}

export type AsceticismScalarWhereInput = {
  AND?: Prisma.AsceticismScalarWhereInput | Prisma.AsceticismScalarWhereInput[]
  OR?: Prisma.AsceticismScalarWhereInput[]
  NOT?: Prisma.AsceticismScalarWhereInput | Prisma.AsceticismScalarWhereInput[]
  id?: Prisma.IntFilter<"Asceticism"> | number
  title?: Prisma.StringFilter<"Asceticism"> | string
  description?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  category?: Prisma.StringFilter<"Asceticism"> | string
  icon?: Prisma.StringNullableFilter<"Asceticism"> | string | null
  isTemplate?: Prisma.BoolFilter<"Asceticism"> | boolean
  creatorId?: Prisma.IntNullableFilter<"Asceticism"> | number | null
  type?: Prisma.EnumTrackingTypeFilter<"Asceticism"> | $Enums.TrackingType
  metadata?: Prisma.JsonNullableFilter<"Asceticism">
  createdAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Asceticism"> | Date | string
}

export type AsceticismCreateWithoutUserAsceticismsInput = {
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  programItems?: Prisma.ProgramItemCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemCreateNestedManyWithoutAsceticismInput
  creator?: Prisma.UserCreateNestedOneWithoutCreatedAsceticismsInput
}

export type AsceticismUncheckedCreateWithoutUserAsceticismsInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  creatorId?: number | null
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  programItems?: Prisma.ProgramItemUncheckedCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemUncheckedCreateNestedManyWithoutAsceticismInput
}

export type AsceticismCreateOrConnectWithoutUserAsceticismsInput = {
  where: Prisma.AsceticismWhereUniqueInput
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedCreateWithoutUserAsceticismsInput>
}

export type AsceticismUpsertWithoutUserAsceticismsInput = {
  update: Prisma.XOR<Prisma.AsceticismUpdateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedUpdateWithoutUserAsceticismsInput>
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedCreateWithoutUserAsceticismsInput>
  where?: Prisma.AsceticismWhereInput
}

export type AsceticismUpdateToOneWithWhereWithoutUserAsceticismsInput = {
  where?: Prisma.AsceticismWhereInput
  data: Prisma.XOR<Prisma.AsceticismUpdateWithoutUserAsceticismsInput, Prisma.AsceticismUncheckedUpdateWithoutUserAsceticismsInput>
}

export type AsceticismUpdateWithoutUserAsceticismsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programItems?: Prisma.ProgramItemUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUpdateManyWithoutAsceticismNestedInput
  creator?: Prisma.UserUpdateOneWithoutCreatedAsceticismsNestedInput
}

export type AsceticismUncheckedUpdateWithoutUserAsceticismsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creatorId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  programItems?: Prisma.ProgramItemUncheckedUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUncheckedUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismCreateWithoutPackageItemsInput = {
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemCreateNestedManyWithoutAsceticismInput
  creator?: Prisma.UserCreateNestedOneWithoutCreatedAsceticismsInput
}

export type AsceticismUncheckedCreateWithoutPackageItemsInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  creatorId?: number | null
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutAsceticismInput
  programItems?: Prisma.ProgramItemUncheckedCreateNestedManyWithoutAsceticismInput
}

export type AsceticismCreateOrConnectWithoutPackageItemsInput = {
  where: Prisma.AsceticismWhereUniqueInput
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutPackageItemsInput, Prisma.AsceticismUncheckedCreateWithoutPackageItemsInput>
}

export type AsceticismUpsertWithoutPackageItemsInput = {
  update: Prisma.XOR<Prisma.AsceticismUpdateWithoutPackageItemsInput, Prisma.AsceticismUncheckedUpdateWithoutPackageItemsInput>
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutPackageItemsInput, Prisma.AsceticismUncheckedCreateWithoutPackageItemsInput>
  where?: Prisma.AsceticismWhereInput
}

export type AsceticismUpdateToOneWithWhereWithoutPackageItemsInput = {
  where?: Prisma.AsceticismWhereInput
  data: Prisma.XOR<Prisma.AsceticismUpdateWithoutPackageItemsInput, Prisma.AsceticismUncheckedUpdateWithoutPackageItemsInput>
}

export type AsceticismUpdateWithoutPackageItemsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUpdateManyWithoutAsceticismNestedInput
  creator?: Prisma.UserUpdateOneWithoutCreatedAsceticismsNestedInput
}

export type AsceticismUncheckedUpdateWithoutPackageItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creatorId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUncheckedUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismCreateWithoutProgramItemsInput = {
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemCreateNestedManyWithoutAsceticismInput
  creator?: Prisma.UserCreateNestedOneWithoutCreatedAsceticismsInput
}

export type AsceticismUncheckedCreateWithoutProgramItemsInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  creatorId?: number | null
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutAsceticismInput
  packageItems?: Prisma.PackageItemUncheckedCreateNestedManyWithoutAsceticismInput
}

export type AsceticismCreateOrConnectWithoutProgramItemsInput = {
  where: Prisma.AsceticismWhereUniqueInput
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutProgramItemsInput, Prisma.AsceticismUncheckedCreateWithoutProgramItemsInput>
}

export type AsceticismUpsertWithoutProgramItemsInput = {
  update: Prisma.XOR<Prisma.AsceticismUpdateWithoutProgramItemsInput, Prisma.AsceticismUncheckedUpdateWithoutProgramItemsInput>
  create: Prisma.XOR<Prisma.AsceticismCreateWithoutProgramItemsInput, Prisma.AsceticismUncheckedCreateWithoutProgramItemsInput>
  where?: Prisma.AsceticismWhereInput
}

export type AsceticismUpdateToOneWithWhereWithoutProgramItemsInput = {
  where?: Prisma.AsceticismWhereInput
  data: Prisma.XOR<Prisma.AsceticismUpdateWithoutProgramItemsInput, Prisma.AsceticismUncheckedUpdateWithoutProgramItemsInput>
}

export type AsceticismUpdateWithoutProgramItemsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUpdateManyWithoutAsceticismNestedInput
  creator?: Prisma.UserUpdateOneWithoutCreatedAsceticismsNestedInput
}

export type AsceticismUncheckedUpdateWithoutProgramItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creatorId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUncheckedUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismCreateManyCreatorInput = {
  id?: number
  title: string
  description?: string | null
  category: string
  icon?: string | null
  isTemplate?: boolean
  type?: $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AsceticismUpdateWithoutCreatorInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismUncheckedUpdateWithoutCreatorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutAsceticismNestedInput
  programItems?: Prisma.ProgramItemUncheckedUpdateManyWithoutAsceticismNestedInput
  packageItems?: Prisma.PackageItemUncheckedUpdateManyWithoutAsceticismNestedInput
}

export type AsceticismUncheckedUpdateManyWithoutCreatorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isTemplate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.EnumTrackingTypeFieldUpdateOperationsInput | $Enums.TrackingType
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AsceticismCountOutputType
 */

export type AsceticismCountOutputType = {
  userAsceticisms: number
  programItems: number
  packageItems: number
}

export type AsceticismCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAsceticisms?: boolean | AsceticismCountOutputTypeCountUserAsceticismsArgs
  programItems?: boolean | AsceticismCountOutputTypeCountProgramItemsArgs
  packageItems?: boolean | AsceticismCountOutputTypeCountPackageItemsArgs
}

/**
 * AsceticismCountOutputType without action
 */
export type AsceticismCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismCountOutputType
   */
  select?: Prisma.AsceticismCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AsceticismCountOutputType without action
 */
export type AsceticismCountOutputTypeCountUserAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserAsceticismWhereInput
}

/**
 * AsceticismCountOutputType without action
 */
export type AsceticismCountOutputTypeCountProgramItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgramItemWhereInput
}

/**
 * AsceticismCountOutputType without action
 */
export type AsceticismCountOutputTypeCountPackageItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackageItemWhereInput
}


export type AsceticismSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  icon?: boolean
  isTemplate?: boolean
  creatorId?: boolean
  type?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userAsceticisms?: boolean | Prisma.Asceticism$userAsceticismsArgs<ExtArgs>
  programItems?: boolean | Prisma.Asceticism$programItemsArgs<ExtArgs>
  packageItems?: boolean | Prisma.Asceticism$packageItemsArgs<ExtArgs>
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.AsceticismCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asceticism"]>

export type AsceticismSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  icon?: boolean
  isTemplate?: boolean
  creatorId?: boolean
  type?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
}, ExtArgs["result"]["asceticism"]>

export type AsceticismSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  icon?: boolean
  isTemplate?: boolean
  creatorId?: boolean
  type?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
}, ExtArgs["result"]["asceticism"]>

export type AsceticismSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  category?: boolean
  icon?: boolean
  isTemplate?: boolean
  creatorId?: boolean
  type?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AsceticismOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "category" | "icon" | "isTemplate" | "creatorId" | "type" | "metadata" | "createdAt" | "updatedAt", ExtArgs["result"]["asceticism"]>
export type AsceticismInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userAsceticisms?: boolean | Prisma.Asceticism$userAsceticismsArgs<ExtArgs>
  programItems?: boolean | Prisma.Asceticism$programItemsArgs<ExtArgs>
  packageItems?: boolean | Prisma.Asceticism$packageItemsArgs<ExtArgs>
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
  _count?: boolean | Prisma.AsceticismCountOutputTypeDefaultArgs<ExtArgs>
}
export type AsceticismIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
}
export type AsceticismIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creator?: boolean | Prisma.Asceticism$creatorArgs<ExtArgs>
}

export type $AsceticismPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Asceticism"
  objects: {
    userAsceticisms: Prisma.$UserAsceticismPayload<ExtArgs>[]
    programItems: Prisma.$ProgramItemPayload<ExtArgs>[]
    packageItems: Prisma.$PackageItemPayload<ExtArgs>[]
    creator: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    description: string | null
    category: string
    icon: string | null
    isTemplate: boolean
    creatorId: number | null
    type: $Enums.TrackingType
    metadata: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["asceticism"]>
  composites: {}
}

export type AsceticismGetPayload<S extends boolean | null | undefined | AsceticismDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AsceticismPayload, S>

export type AsceticismCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AsceticismFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AsceticismCountAggregateInputType | true
  }

export interface AsceticismDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Asceticism'], meta: { name: 'Asceticism' } }
  /**
   * Find zero or one Asceticism that matches the filter.
   * @param {AsceticismFindUniqueArgs} args - Arguments to find a Asceticism
   * @example
   * // Get one Asceticism
   * const asceticism = await prisma.asceticism.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AsceticismFindUniqueArgs>(args: Prisma.SelectSubset<T, AsceticismFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Asceticism that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AsceticismFindUniqueOrThrowArgs} args - Arguments to find a Asceticism
   * @example
   * // Get one Asceticism
   * const asceticism = await prisma.asceticism.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AsceticismFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AsceticismFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asceticism that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismFindFirstArgs} args - Arguments to find a Asceticism
   * @example
   * // Get one Asceticism
   * const asceticism = await prisma.asceticism.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AsceticismFindFirstArgs>(args?: Prisma.SelectSubset<T, AsceticismFindFirstArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Asceticism that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismFindFirstOrThrowArgs} args - Arguments to find a Asceticism
   * @example
   * // Get one Asceticism
   * const asceticism = await prisma.asceticism.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AsceticismFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AsceticismFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Asceticisms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Asceticisms
   * const asceticisms = await prisma.asceticism.findMany()
   * 
   * // Get first 10 Asceticisms
   * const asceticisms = await prisma.asceticism.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const asceticismWithIdOnly = await prisma.asceticism.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AsceticismFindManyArgs>(args?: Prisma.SelectSubset<T, AsceticismFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Asceticism.
   * @param {AsceticismCreateArgs} args - Arguments to create a Asceticism.
   * @example
   * // Create one Asceticism
   * const Asceticism = await prisma.asceticism.create({
   *   data: {
   *     // ... data to create a Asceticism
   *   }
   * })
   * 
   */
  create<T extends AsceticismCreateArgs>(args: Prisma.SelectSubset<T, AsceticismCreateArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Asceticisms.
   * @param {AsceticismCreateManyArgs} args - Arguments to create many Asceticisms.
   * @example
   * // Create many Asceticisms
   * const asceticism = await prisma.asceticism.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AsceticismCreateManyArgs>(args?: Prisma.SelectSubset<T, AsceticismCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Asceticisms and returns the data saved in the database.
   * @param {AsceticismCreateManyAndReturnArgs} args - Arguments to create many Asceticisms.
   * @example
   * // Create many Asceticisms
   * const asceticism = await prisma.asceticism.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Asceticisms and only return the `id`
   * const asceticismWithIdOnly = await prisma.asceticism.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AsceticismCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AsceticismCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Asceticism.
   * @param {AsceticismDeleteArgs} args - Arguments to delete one Asceticism.
   * @example
   * // Delete one Asceticism
   * const Asceticism = await prisma.asceticism.delete({
   *   where: {
   *     // ... filter to delete one Asceticism
   *   }
   * })
   * 
   */
  delete<T extends AsceticismDeleteArgs>(args: Prisma.SelectSubset<T, AsceticismDeleteArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Asceticism.
   * @param {AsceticismUpdateArgs} args - Arguments to update one Asceticism.
   * @example
   * // Update one Asceticism
   * const asceticism = await prisma.asceticism.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AsceticismUpdateArgs>(args: Prisma.SelectSubset<T, AsceticismUpdateArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Asceticisms.
   * @param {AsceticismDeleteManyArgs} args - Arguments to filter Asceticisms to delete.
   * @example
   * // Delete a few Asceticisms
   * const { count } = await prisma.asceticism.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AsceticismDeleteManyArgs>(args?: Prisma.SelectSubset<T, AsceticismDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Asceticisms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Asceticisms
   * const asceticism = await prisma.asceticism.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AsceticismUpdateManyArgs>(args: Prisma.SelectSubset<T, AsceticismUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Asceticisms and returns the data updated in the database.
   * @param {AsceticismUpdateManyAndReturnArgs} args - Arguments to update many Asceticisms.
   * @example
   * // Update many Asceticisms
   * const asceticism = await prisma.asceticism.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Asceticisms and only return the `id`
   * const asceticismWithIdOnly = await prisma.asceticism.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AsceticismUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AsceticismUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Asceticism.
   * @param {AsceticismUpsertArgs} args - Arguments to update or create a Asceticism.
   * @example
   * // Update or create a Asceticism
   * const asceticism = await prisma.asceticism.upsert({
   *   create: {
   *     // ... data to create a Asceticism
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Asceticism we want to update
   *   }
   * })
   */
  upsert<T extends AsceticismUpsertArgs>(args: Prisma.SelectSubset<T, AsceticismUpsertArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Asceticisms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismCountArgs} args - Arguments to filter Asceticisms to count.
   * @example
   * // Count the number of Asceticisms
   * const count = await prisma.asceticism.count({
   *   where: {
   *     // ... the filter for the Asceticisms we want to count
   *   }
   * })
  **/
  count<T extends AsceticismCountArgs>(
    args?: Prisma.Subset<T, AsceticismCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AsceticismCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Asceticism.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AsceticismAggregateArgs>(args: Prisma.Subset<T, AsceticismAggregateArgs>): Prisma.PrismaPromise<GetAsceticismAggregateType<T>>

  /**
   * Group by Asceticism.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AsceticismGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AsceticismGroupByArgs['orderBy'] }
      : { orderBy?: AsceticismGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AsceticismGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAsceticismGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Asceticism model
 */
readonly fields: AsceticismFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Asceticism.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AsceticismClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  userAsceticisms<T extends Prisma.Asceticism$userAsceticismsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asceticism$userAsceticismsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserAsceticismPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  programItems<T extends Prisma.Asceticism$programItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asceticism$programItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  packageItems<T extends Prisma.Asceticism$packageItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asceticism$packageItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackageItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  creator<T extends Prisma.Asceticism$creatorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Asceticism$creatorArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Asceticism model
 */
export interface AsceticismFieldRefs {
  readonly id: Prisma.FieldRef<"Asceticism", 'Int'>
  readonly title: Prisma.FieldRef<"Asceticism", 'String'>
  readonly description: Prisma.FieldRef<"Asceticism", 'String'>
  readonly category: Prisma.FieldRef<"Asceticism", 'String'>
  readonly icon: Prisma.FieldRef<"Asceticism", 'String'>
  readonly isTemplate: Prisma.FieldRef<"Asceticism", 'Boolean'>
  readonly creatorId: Prisma.FieldRef<"Asceticism", 'Int'>
  readonly type: Prisma.FieldRef<"Asceticism", 'TrackingType'>
  readonly metadata: Prisma.FieldRef<"Asceticism", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Asceticism", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Asceticism", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Asceticism findUnique
 */
export type AsceticismFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter, which Asceticism to fetch.
   */
  where: Prisma.AsceticismWhereUniqueInput
}

/**
 * Asceticism findUniqueOrThrow
 */
export type AsceticismFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter, which Asceticism to fetch.
   */
  where: Prisma.AsceticismWhereUniqueInput
}

/**
 * Asceticism findFirst
 */
export type AsceticismFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter, which Asceticism to fetch.
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Asceticisms to fetch.
   */
  orderBy?: Prisma.AsceticismOrderByWithRelationInput | Prisma.AsceticismOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Asceticisms.
   */
  cursor?: Prisma.AsceticismWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Asceticisms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Asceticisms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Asceticisms.
   */
  distinct?: Prisma.AsceticismScalarFieldEnum | Prisma.AsceticismScalarFieldEnum[]
}

/**
 * Asceticism findFirstOrThrow
 */
export type AsceticismFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter, which Asceticism to fetch.
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Asceticisms to fetch.
   */
  orderBy?: Prisma.AsceticismOrderByWithRelationInput | Prisma.AsceticismOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Asceticisms.
   */
  cursor?: Prisma.AsceticismWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Asceticisms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Asceticisms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Asceticisms.
   */
  distinct?: Prisma.AsceticismScalarFieldEnum | Prisma.AsceticismScalarFieldEnum[]
}

/**
 * Asceticism findMany
 */
export type AsceticismFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter, which Asceticisms to fetch.
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Asceticisms to fetch.
   */
  orderBy?: Prisma.AsceticismOrderByWithRelationInput | Prisma.AsceticismOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Asceticisms.
   */
  cursor?: Prisma.AsceticismWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Asceticisms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Asceticisms.
   */
  skip?: number
  distinct?: Prisma.AsceticismScalarFieldEnum | Prisma.AsceticismScalarFieldEnum[]
}

/**
 * Asceticism create
 */
export type AsceticismCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * The data needed to create a Asceticism.
   */
  data: Prisma.XOR<Prisma.AsceticismCreateInput, Prisma.AsceticismUncheckedCreateInput>
}

/**
 * Asceticism createMany
 */
export type AsceticismCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Asceticisms.
   */
  data: Prisma.AsceticismCreateManyInput | Prisma.AsceticismCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Asceticism createManyAndReturn
 */
export type AsceticismCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * The data used to create many Asceticisms.
   */
  data: Prisma.AsceticismCreateManyInput | Prisma.AsceticismCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Asceticism update
 */
export type AsceticismUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * The data needed to update a Asceticism.
   */
  data: Prisma.XOR<Prisma.AsceticismUpdateInput, Prisma.AsceticismUncheckedUpdateInput>
  /**
   * Choose, which Asceticism to update.
   */
  where: Prisma.AsceticismWhereUniqueInput
}

/**
 * Asceticism updateMany
 */
export type AsceticismUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Asceticisms.
   */
  data: Prisma.XOR<Prisma.AsceticismUpdateManyMutationInput, Prisma.AsceticismUncheckedUpdateManyInput>
  /**
   * Filter which Asceticisms to update
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * Limit how many Asceticisms to update.
   */
  limit?: number
}

/**
 * Asceticism updateManyAndReturn
 */
export type AsceticismUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * The data used to update Asceticisms.
   */
  data: Prisma.XOR<Prisma.AsceticismUpdateManyMutationInput, Prisma.AsceticismUncheckedUpdateManyInput>
  /**
   * Filter which Asceticisms to update
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * Limit how many Asceticisms to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Asceticism upsert
 */
export type AsceticismUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * The filter to search for the Asceticism to update in case it exists.
   */
  where: Prisma.AsceticismWhereUniqueInput
  /**
   * In case the Asceticism found by the `where` argument doesn't exist, create a new Asceticism with this data.
   */
  create: Prisma.XOR<Prisma.AsceticismCreateInput, Prisma.AsceticismUncheckedCreateInput>
  /**
   * In case the Asceticism was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AsceticismUpdateInput, Prisma.AsceticismUncheckedUpdateInput>
}

/**
 * Asceticism delete
 */
export type AsceticismDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  /**
   * Filter which Asceticism to delete.
   */
  where: Prisma.AsceticismWhereUniqueInput
}

/**
 * Asceticism deleteMany
 */
export type AsceticismDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Asceticisms to delete
   */
  where?: Prisma.AsceticismWhereInput
  /**
   * Limit how many Asceticisms to delete.
   */
  limit?: number
}

/**
 * Asceticism.userAsceticisms
 */
export type Asceticism$userAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAsceticism
   */
  select?: Prisma.UserAsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAsceticism
   */
  omit?: Prisma.UserAsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserAsceticismInclude<ExtArgs> | null
  where?: Prisma.UserAsceticismWhereInput
  orderBy?: Prisma.UserAsceticismOrderByWithRelationInput | Prisma.UserAsceticismOrderByWithRelationInput[]
  cursor?: Prisma.UserAsceticismWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserAsceticismScalarFieldEnum | Prisma.UserAsceticismScalarFieldEnum[]
}

/**
 * Asceticism.programItems
 */
export type Asceticism$programItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  where?: Prisma.ProgramItemWhereInput
  orderBy?: Prisma.ProgramItemOrderByWithRelationInput | Prisma.ProgramItemOrderByWithRelationInput[]
  cursor?: Prisma.ProgramItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProgramItemScalarFieldEnum | Prisma.ProgramItemScalarFieldEnum[]
}

/**
 * Asceticism.packageItems
 */
export type Asceticism$packageItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackageItem
   */
  select?: Prisma.PackageItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackageItem
   */
  omit?: Prisma.PackageItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackageItemInclude<ExtArgs> | null
  where?: Prisma.PackageItemWhereInput
  orderBy?: Prisma.PackageItemOrderByWithRelationInput | Prisma.PackageItemOrderByWithRelationInput[]
  cursor?: Prisma.PackageItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackageItemScalarFieldEnum | Prisma.PackageItemScalarFieldEnum[]
}

/**
 * Asceticism.creator
 */
export type Asceticism$creatorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Asceticism without action
 */
export type AsceticismDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
}
