
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AsceticismPackage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AsceticismPackage
 * 
 */
export type AsceticismPackageModel = runtime.Types.Result.DefaultSelection<Prisma.$AsceticismPackagePayload>

export type AggregateAsceticismPackage = {
  _count: AsceticismPackageCountAggregateOutputType | null
  _avg: AsceticismPackageAvgAggregateOutputType | null
  _sum: AsceticismPackageSumAggregateOutputType | null
  _min: AsceticismPackageMinAggregateOutputType | null
  _max: AsceticismPackageMaxAggregateOutputType | null
}

export type AsceticismPackageAvgAggregateOutputType = {
  id: number | null
  creatorId: number | null
}

export type AsceticismPackageSumAggregateOutputType = {
  id: number | null
  creatorId: number | null
}

export type AsceticismPackageMinAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  creatorId: number | null
  isPublished: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AsceticismPackageMaxAggregateOutputType = {
  id: number | null
  title: string | null
  description: string | null
  creatorId: number | null
  isPublished: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AsceticismPackageCountAggregateOutputType = {
  id: number
  title: number
  description: number
  creatorId: number
  isPublished: number
  metadata: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AsceticismPackageAvgAggregateInputType = {
  id?: true
  creatorId?: true
}

export type AsceticismPackageSumAggregateInputType = {
  id?: true
  creatorId?: true
}

export type AsceticismPackageMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  creatorId?: true
  isPublished?: true
  createdAt?: true
  updatedAt?: true
}

export type AsceticismPackageMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  creatorId?: true
  isPublished?: true
  createdAt?: true
  updatedAt?: true
}

export type AsceticismPackageCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  creatorId?: true
  isPublished?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AsceticismPackageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AsceticismPackage to aggregate.
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AsceticismPackages to fetch.
   */
  orderBy?: Prisma.AsceticismPackageOrderByWithRelationInput | Prisma.AsceticismPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AsceticismPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AsceticismPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AsceticismPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AsceticismPackages
  **/
  _count?: true | AsceticismPackageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AsceticismPackageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AsceticismPackageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AsceticismPackageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AsceticismPackageMaxAggregateInputType
}

export type GetAsceticismPackageAggregateType<T extends AsceticismPackageAggregateArgs> = {
      [P in keyof T & keyof AggregateAsceticismPackage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAsceticismPackage[P]>
    : Prisma.GetScalarType<T[P], AggregateAsceticismPackage[P]>
}




export type AsceticismPackageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AsceticismPackageWhereInput
  orderBy?: Prisma.AsceticismPackageOrderByWithAggregationInput | Prisma.AsceticismPackageOrderByWithAggregationInput[]
  by: Prisma.AsceticismPackageScalarFieldEnum[] | Prisma.AsceticismPackageScalarFieldEnum
  having?: Prisma.AsceticismPackageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AsceticismPackageCountAggregateInputType | true
  _avg?: AsceticismPackageAvgAggregateInputType
  _sum?: AsceticismPackageSumAggregateInputType
  _min?: AsceticismPackageMinAggregateInputType
  _max?: AsceticismPackageMaxAggregateInputType
}

export type AsceticismPackageGroupByOutputType = {
  id: number
  title: string
  description: string | null
  creatorId: number
  isPublished: boolean
  metadata: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: AsceticismPackageCountAggregateOutputType | null
  _avg: AsceticismPackageAvgAggregateOutputType | null
  _sum: AsceticismPackageSumAggregateOutputType | null
  _min: AsceticismPackageMinAggregateOutputType | null
  _max: AsceticismPackageMaxAggregateOutputType | null
}

type GetAsceticismPackageGroupByPayload<T extends AsceticismPackageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AsceticismPackageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AsceticismPackageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AsceticismPackageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AsceticismPackageGroupByOutputType[P]>
      }
    >
  >



export type AsceticismPackageWhereInput = {
  AND?: Prisma.AsceticismPackageWhereInput | Prisma.AsceticismPackageWhereInput[]
  OR?: Prisma.AsceticismPackageWhereInput[]
  NOT?: Prisma.AsceticismPackageWhereInput | Prisma.AsceticismPackageWhereInput[]
  id?: Prisma.IntFilter<"AsceticismPackage"> | number
  title?: Prisma.StringFilter<"AsceticismPackage"> | string
  description?: Prisma.StringNullableFilter<"AsceticismPackage"> | string | null
  creatorId?: Prisma.IntFilter<"AsceticismPackage"> | number
  isPublished?: Prisma.BoolFilter<"AsceticismPackage"> | boolean
  metadata?: Prisma.JsonNullableFilter<"AsceticismPackage">
  createdAt?: Prisma.DateTimeFilter<"AsceticismPackage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AsceticismPackage"> | Date | string
  items?: Prisma.PackageItemListRelationFilter
}

export type AsceticismPackageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  items?: Prisma.PackageItemOrderByRelationAggregateInput
}

export type AsceticismPackageWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AsceticismPackageWhereInput | Prisma.AsceticismPackageWhereInput[]
  OR?: Prisma.AsceticismPackageWhereInput[]
  NOT?: Prisma.AsceticismPackageWhereInput | Prisma.AsceticismPackageWhereInput[]
  title?: Prisma.StringFilter<"AsceticismPackage"> | string
  description?: Prisma.StringNullableFilter<"AsceticismPackage"> | string | null
  creatorId?: Prisma.IntFilter<"AsceticismPackage"> | number
  isPublished?: Prisma.BoolFilter<"AsceticismPackage"> | boolean
  metadata?: Prisma.JsonNullableFilter<"AsceticismPackage">
  createdAt?: Prisma.DateTimeFilter<"AsceticismPackage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AsceticismPackage"> | Date | string
  items?: Prisma.PackageItemListRelationFilter
}, "id">

export type AsceticismPackageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AsceticismPackageCountOrderByAggregateInput
  _avg?: Prisma.AsceticismPackageAvgOrderByAggregateInput
  _max?: Prisma.AsceticismPackageMaxOrderByAggregateInput
  _min?: Prisma.AsceticismPackageMinOrderByAggregateInput
  _sum?: Prisma.AsceticismPackageSumOrderByAggregateInput
}

export type AsceticismPackageScalarWhereWithAggregatesInput = {
  AND?: Prisma.AsceticismPackageScalarWhereWithAggregatesInput | Prisma.AsceticismPackageScalarWhereWithAggregatesInput[]
  OR?: Prisma.AsceticismPackageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AsceticismPackageScalarWhereWithAggregatesInput | Prisma.AsceticismPackageScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AsceticismPackage"> | number
  title?: Prisma.StringWithAggregatesFilter<"AsceticismPackage"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"AsceticismPackage"> | string | null
  creatorId?: Prisma.IntWithAggregatesFilter<"AsceticismPackage"> | number
  isPublished?: Prisma.BoolWithAggregatesFilter<"AsceticismPackage"> | boolean
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"AsceticismPackage">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AsceticismPackage"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AsceticismPackage"> | Date | string
}

export type AsceticismPackageCreateInput = {
  title: string
  description?: string | null
  creatorId: number
  isPublished?: boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.PackageItemCreateNestedManyWithoutPackageInput
}

export type AsceticismPackageUncheckedCreateInput = {
  id?: number
  title: string
  description?: string | null
  creatorId: number
  isPublished?: boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.PackageItemUncheckedCreateNestedManyWithoutPackageInput
}

export type AsceticismPackageUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.PackageItemUpdateManyWithoutPackageNestedInput
}

export type AsceticismPackageUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.PackageItemUncheckedUpdateManyWithoutPackageNestedInput
}

export type AsceticismPackageCreateManyInput = {
  id?: number
  title: string
  description?: string | null
  creatorId: number
  isPublished?: boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AsceticismPackageUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AsceticismPackageUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AsceticismPackageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismPackageAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
}

export type AsceticismPackageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismPackageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
  isPublished?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AsceticismPackageSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  creatorId?: Prisma.SortOrder
}

export type AsceticismPackageScalarRelationFilter = {
  is?: Prisma.AsceticismPackageWhereInput
  isNot?: Prisma.AsceticismPackageWhereInput
}

export type AsceticismPackageCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.AsceticismPackageCreateWithoutItemsInput, Prisma.AsceticismPackageUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.AsceticismPackageCreateOrConnectWithoutItemsInput
  connect?: Prisma.AsceticismPackageWhereUniqueInput
}

export type AsceticismPackageUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.AsceticismPackageCreateWithoutItemsInput, Prisma.AsceticismPackageUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.AsceticismPackageCreateOrConnectWithoutItemsInput
  upsert?: Prisma.AsceticismPackageUpsertWithoutItemsInput
  connect?: Prisma.AsceticismPackageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AsceticismPackageUpdateToOneWithWhereWithoutItemsInput, Prisma.AsceticismPackageUpdateWithoutItemsInput>, Prisma.AsceticismPackageUncheckedUpdateWithoutItemsInput>
}

export type AsceticismPackageCreateWithoutItemsInput = {
  title: string
  description?: string | null
  creatorId: number
  isPublished?: boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AsceticismPackageUncheckedCreateWithoutItemsInput = {
  id?: number
  title: string
  description?: string | null
  creatorId: number
  isPublished?: boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AsceticismPackageCreateOrConnectWithoutItemsInput = {
  where: Prisma.AsceticismPackageWhereUniqueInput
  create: Prisma.XOR<Prisma.AsceticismPackageCreateWithoutItemsInput, Prisma.AsceticismPackageUncheckedCreateWithoutItemsInput>
}

export type AsceticismPackageUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.AsceticismPackageUpdateWithoutItemsInput, Prisma.AsceticismPackageUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.AsceticismPackageCreateWithoutItemsInput, Prisma.AsceticismPackageUncheckedCreateWithoutItemsInput>
  where?: Prisma.AsceticismPackageWhereInput
}

export type AsceticismPackageUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.AsceticismPackageWhereInput
  data: Prisma.XOR<Prisma.AsceticismPackageUpdateWithoutItemsInput, Prisma.AsceticismPackageUncheckedUpdateWithoutItemsInput>
}

export type AsceticismPackageUpdateWithoutItemsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AsceticismPackageUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  creatorId?: Prisma.IntFieldUpdateOperationsInput | number
  isPublished?: Prisma.BoolFieldUpdateOperationsInput | boolean
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AsceticismPackageCountOutputType
 */

export type AsceticismPackageCountOutputType = {
  items: number
}

export type AsceticismPackageCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | AsceticismPackageCountOutputTypeCountItemsArgs
}

/**
 * AsceticismPackageCountOutputType without action
 */
export type AsceticismPackageCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackageCountOutputType
   */
  select?: Prisma.AsceticismPackageCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AsceticismPackageCountOutputType without action
 */
export type AsceticismPackageCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PackageItemWhereInput
}


export type AsceticismPackageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  creatorId?: boolean
  isPublished?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  items?: boolean | Prisma.AsceticismPackage$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.AsceticismPackageCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["asceticismPackage"]>

export type AsceticismPackageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  creatorId?: boolean
  isPublished?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["asceticismPackage"]>

export type AsceticismPackageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  creatorId?: boolean
  isPublished?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["asceticismPackage"]>

export type AsceticismPackageSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  creatorId?: boolean
  isPublished?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AsceticismPackageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "creatorId" | "isPublished" | "metadata" | "createdAt" | "updatedAt", ExtArgs["result"]["asceticismPackage"]>
export type AsceticismPackageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | Prisma.AsceticismPackage$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.AsceticismPackageCountOutputTypeDefaultArgs<ExtArgs>
}
export type AsceticismPackageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AsceticismPackageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AsceticismPackagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AsceticismPackage"
  objects: {
    items: Prisma.$PackageItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    description: string | null
    creatorId: number
    isPublished: boolean
    metadata: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["asceticismPackage"]>
  composites: {}
}

export type AsceticismPackageGetPayload<S extends boolean | null | undefined | AsceticismPackageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload, S>

export type AsceticismPackageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AsceticismPackageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AsceticismPackageCountAggregateInputType | true
  }

export interface AsceticismPackageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AsceticismPackage'], meta: { name: 'AsceticismPackage' } }
  /**
   * Find zero or one AsceticismPackage that matches the filter.
   * @param {AsceticismPackageFindUniqueArgs} args - Arguments to find a AsceticismPackage
   * @example
   * // Get one AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AsceticismPackageFindUniqueArgs>(args: Prisma.SelectSubset<T, AsceticismPackageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AsceticismPackage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AsceticismPackageFindUniqueOrThrowArgs} args - Arguments to find a AsceticismPackage
   * @example
   * // Get one AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AsceticismPackageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AsceticismPackageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AsceticismPackage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageFindFirstArgs} args - Arguments to find a AsceticismPackage
   * @example
   * // Get one AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AsceticismPackageFindFirstArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageFindFirstArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AsceticismPackage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageFindFirstOrThrowArgs} args - Arguments to find a AsceticismPackage
   * @example
   * // Get one AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AsceticismPackageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AsceticismPackages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AsceticismPackages
   * const asceticismPackages = await prisma.asceticismPackage.findMany()
   * 
   * // Get first 10 AsceticismPackages
   * const asceticismPackages = await prisma.asceticismPackage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const asceticismPackageWithIdOnly = await prisma.asceticismPackage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AsceticismPackageFindManyArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AsceticismPackage.
   * @param {AsceticismPackageCreateArgs} args - Arguments to create a AsceticismPackage.
   * @example
   * // Create one AsceticismPackage
   * const AsceticismPackage = await prisma.asceticismPackage.create({
   *   data: {
   *     // ... data to create a AsceticismPackage
   *   }
   * })
   * 
   */
  create<T extends AsceticismPackageCreateArgs>(args: Prisma.SelectSubset<T, AsceticismPackageCreateArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AsceticismPackages.
   * @param {AsceticismPackageCreateManyArgs} args - Arguments to create many AsceticismPackages.
   * @example
   * // Create many AsceticismPackages
   * const asceticismPackage = await prisma.asceticismPackage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AsceticismPackageCreateManyArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AsceticismPackages and returns the data saved in the database.
   * @param {AsceticismPackageCreateManyAndReturnArgs} args - Arguments to create many AsceticismPackages.
   * @example
   * // Create many AsceticismPackages
   * const asceticismPackage = await prisma.asceticismPackage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AsceticismPackages and only return the `id`
   * const asceticismPackageWithIdOnly = await prisma.asceticismPackage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AsceticismPackageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AsceticismPackage.
   * @param {AsceticismPackageDeleteArgs} args - Arguments to delete one AsceticismPackage.
   * @example
   * // Delete one AsceticismPackage
   * const AsceticismPackage = await prisma.asceticismPackage.delete({
   *   where: {
   *     // ... filter to delete one AsceticismPackage
   *   }
   * })
   * 
   */
  delete<T extends AsceticismPackageDeleteArgs>(args: Prisma.SelectSubset<T, AsceticismPackageDeleteArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AsceticismPackage.
   * @param {AsceticismPackageUpdateArgs} args - Arguments to update one AsceticismPackage.
   * @example
   * // Update one AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AsceticismPackageUpdateArgs>(args: Prisma.SelectSubset<T, AsceticismPackageUpdateArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AsceticismPackages.
   * @param {AsceticismPackageDeleteManyArgs} args - Arguments to filter AsceticismPackages to delete.
   * @example
   * // Delete a few AsceticismPackages
   * const { count } = await prisma.asceticismPackage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AsceticismPackageDeleteManyArgs>(args?: Prisma.SelectSubset<T, AsceticismPackageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AsceticismPackages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AsceticismPackages
   * const asceticismPackage = await prisma.asceticismPackage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AsceticismPackageUpdateManyArgs>(args: Prisma.SelectSubset<T, AsceticismPackageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AsceticismPackages and returns the data updated in the database.
   * @param {AsceticismPackageUpdateManyAndReturnArgs} args - Arguments to update many AsceticismPackages.
   * @example
   * // Update many AsceticismPackages
   * const asceticismPackage = await prisma.asceticismPackage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AsceticismPackages and only return the `id`
   * const asceticismPackageWithIdOnly = await prisma.asceticismPackage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AsceticismPackageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AsceticismPackageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AsceticismPackage.
   * @param {AsceticismPackageUpsertArgs} args - Arguments to update or create a AsceticismPackage.
   * @example
   * // Update or create a AsceticismPackage
   * const asceticismPackage = await prisma.asceticismPackage.upsert({
   *   create: {
   *     // ... data to create a AsceticismPackage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AsceticismPackage we want to update
   *   }
   * })
   */
  upsert<T extends AsceticismPackageUpsertArgs>(args: Prisma.SelectSubset<T, AsceticismPackageUpsertArgs<ExtArgs>>): Prisma.Prisma__AsceticismPackageClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPackagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AsceticismPackages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageCountArgs} args - Arguments to filter AsceticismPackages to count.
   * @example
   * // Count the number of AsceticismPackages
   * const count = await prisma.asceticismPackage.count({
   *   where: {
   *     // ... the filter for the AsceticismPackages we want to count
   *   }
   * })
  **/
  count<T extends AsceticismPackageCountArgs>(
    args?: Prisma.Subset<T, AsceticismPackageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AsceticismPackageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AsceticismPackage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AsceticismPackageAggregateArgs>(args: Prisma.Subset<T, AsceticismPackageAggregateArgs>): Prisma.PrismaPromise<GetAsceticismPackageAggregateType<T>>

  /**
   * Group by AsceticismPackage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AsceticismPackageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AsceticismPackageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AsceticismPackageGroupByArgs['orderBy'] }
      : { orderBy?: AsceticismPackageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AsceticismPackageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAsceticismPackageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AsceticismPackage model
 */
readonly fields: AsceticismPackageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AsceticismPackage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AsceticismPackageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  items<T extends Prisma.AsceticismPackage$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AsceticismPackage$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PackageItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AsceticismPackage model
 */
export interface AsceticismPackageFieldRefs {
  readonly id: Prisma.FieldRef<"AsceticismPackage", 'Int'>
  readonly title: Prisma.FieldRef<"AsceticismPackage", 'String'>
  readonly description: Prisma.FieldRef<"AsceticismPackage", 'String'>
  readonly creatorId: Prisma.FieldRef<"AsceticismPackage", 'Int'>
  readonly isPublished: Prisma.FieldRef<"AsceticismPackage", 'Boolean'>
  readonly metadata: Prisma.FieldRef<"AsceticismPackage", 'Json'>
  readonly createdAt: Prisma.FieldRef<"AsceticismPackage", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AsceticismPackage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AsceticismPackage findUnique
 */
export type AsceticismPackageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter, which AsceticismPackage to fetch.
   */
  where: Prisma.AsceticismPackageWhereUniqueInput
}

/**
 * AsceticismPackage findUniqueOrThrow
 */
export type AsceticismPackageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter, which AsceticismPackage to fetch.
   */
  where: Prisma.AsceticismPackageWhereUniqueInput
}

/**
 * AsceticismPackage findFirst
 */
export type AsceticismPackageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter, which AsceticismPackage to fetch.
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AsceticismPackages to fetch.
   */
  orderBy?: Prisma.AsceticismPackageOrderByWithRelationInput | Prisma.AsceticismPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AsceticismPackages.
   */
  cursor?: Prisma.AsceticismPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AsceticismPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AsceticismPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AsceticismPackages.
   */
  distinct?: Prisma.AsceticismPackageScalarFieldEnum | Prisma.AsceticismPackageScalarFieldEnum[]
}

/**
 * AsceticismPackage findFirstOrThrow
 */
export type AsceticismPackageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter, which AsceticismPackage to fetch.
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AsceticismPackages to fetch.
   */
  orderBy?: Prisma.AsceticismPackageOrderByWithRelationInput | Prisma.AsceticismPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AsceticismPackages.
   */
  cursor?: Prisma.AsceticismPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AsceticismPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AsceticismPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AsceticismPackages.
   */
  distinct?: Prisma.AsceticismPackageScalarFieldEnum | Prisma.AsceticismPackageScalarFieldEnum[]
}

/**
 * AsceticismPackage findMany
 */
export type AsceticismPackageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter, which AsceticismPackages to fetch.
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AsceticismPackages to fetch.
   */
  orderBy?: Prisma.AsceticismPackageOrderByWithRelationInput | Prisma.AsceticismPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AsceticismPackages.
   */
  cursor?: Prisma.AsceticismPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AsceticismPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AsceticismPackages.
   */
  skip?: number
  distinct?: Prisma.AsceticismPackageScalarFieldEnum | Prisma.AsceticismPackageScalarFieldEnum[]
}

/**
 * AsceticismPackage create
 */
export type AsceticismPackageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * The data needed to create a AsceticismPackage.
   */
  data: Prisma.XOR<Prisma.AsceticismPackageCreateInput, Prisma.AsceticismPackageUncheckedCreateInput>
}

/**
 * AsceticismPackage createMany
 */
export type AsceticismPackageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AsceticismPackages.
   */
  data: Prisma.AsceticismPackageCreateManyInput | Prisma.AsceticismPackageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AsceticismPackage createManyAndReturn
 */
export type AsceticismPackageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * The data used to create many AsceticismPackages.
   */
  data: Prisma.AsceticismPackageCreateManyInput | Prisma.AsceticismPackageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AsceticismPackage update
 */
export type AsceticismPackageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * The data needed to update a AsceticismPackage.
   */
  data: Prisma.XOR<Prisma.AsceticismPackageUpdateInput, Prisma.AsceticismPackageUncheckedUpdateInput>
  /**
   * Choose, which AsceticismPackage to update.
   */
  where: Prisma.AsceticismPackageWhereUniqueInput
}

/**
 * AsceticismPackage updateMany
 */
export type AsceticismPackageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AsceticismPackages.
   */
  data: Prisma.XOR<Prisma.AsceticismPackageUpdateManyMutationInput, Prisma.AsceticismPackageUncheckedUpdateManyInput>
  /**
   * Filter which AsceticismPackages to update
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * Limit how many AsceticismPackages to update.
   */
  limit?: number
}

/**
 * AsceticismPackage updateManyAndReturn
 */
export type AsceticismPackageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * The data used to update AsceticismPackages.
   */
  data: Prisma.XOR<Prisma.AsceticismPackageUpdateManyMutationInput, Prisma.AsceticismPackageUncheckedUpdateManyInput>
  /**
   * Filter which AsceticismPackages to update
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * Limit how many AsceticismPackages to update.
   */
  limit?: number
}

/**
 * AsceticismPackage upsert
 */
export type AsceticismPackageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * The filter to search for the AsceticismPackage to update in case it exists.
   */
  where: Prisma.AsceticismPackageWhereUniqueInput
  /**
   * In case the AsceticismPackage found by the `where` argument doesn't exist, create a new AsceticismPackage with this data.
   */
  create: Prisma.XOR<Prisma.AsceticismPackageCreateInput, Prisma.AsceticismPackageUncheckedCreateInput>
  /**
   * In case the AsceticismPackage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AsceticismPackageUpdateInput, Prisma.AsceticismPackageUncheckedUpdateInput>
}

/**
 * AsceticismPackage delete
 */
export type AsceticismPackageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
  /**
   * Filter which AsceticismPackage to delete.
   */
  where: Prisma.AsceticismPackageWhereUniqueInput
}

/**
 * AsceticismPackage deleteMany
 */
export type AsceticismPackageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AsceticismPackages to delete
   */
  where?: Prisma.AsceticismPackageWhereInput
  /**
   * Limit how many AsceticismPackages to delete.
   */
  limit?: number
}

/**
 * AsceticismPackage.items
 */
export type AsceticismPackage$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PackageItem
   */
  select?: Prisma.PackageItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PackageItem
   */
  omit?: Prisma.PackageItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PackageItemInclude<ExtArgs> | null
  where?: Prisma.PackageItemWhereInput
  orderBy?: Prisma.PackageItemOrderByWithRelationInput | Prisma.PackageItemOrderByWithRelationInput[]
  cursor?: Prisma.PackageItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PackageItemScalarFieldEnum | Prisma.PackageItemScalarFieldEnum[]
}

/**
 * AsceticismPackage without action
 */
export type AsceticismPackageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AsceticismPackage
   */
  select?: Prisma.AsceticismPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AsceticismPackage
   */
  omit?: Prisma.AsceticismPackageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismPackageInclude<ExtArgs> | null
}
