
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProgramItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProgramItem
 * 
 */
export type ProgramItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ProgramItemPayload>

export type AggregateProgramItem = {
  _count: ProgramItemCountAggregateOutputType | null
  _avg: ProgramItemAvgAggregateOutputType | null
  _sum: ProgramItemSumAggregateOutputType | null
  _min: ProgramItemMinAggregateOutputType | null
  _max: ProgramItemMaxAggregateOutputType | null
}

export type ProgramItemAvgAggregateOutputType = {
  id: number | null
  programId: number | null
  asceticismId: number | null
  dayStart: number | null
  dayEnd: number | null
}

export type ProgramItemSumAggregateOutputType = {
  id: number | null
  programId: number | null
  asceticismId: number | null
  dayStart: number | null
  dayEnd: number | null
}

export type ProgramItemMinAggregateOutputType = {
  id: number | null
  programId: number | null
  asceticismId: number | null
  dayStart: number | null
  dayEnd: number | null
}

export type ProgramItemMaxAggregateOutputType = {
  id: number | null
  programId: number | null
  asceticismId: number | null
  dayStart: number | null
  dayEnd: number | null
}

export type ProgramItemCountAggregateOutputType = {
  id: number
  programId: number
  asceticismId: number
  dayStart: number
  dayEnd: number
  metadata: number
  _all: number
}


export type ProgramItemAvgAggregateInputType = {
  id?: true
  programId?: true
  asceticismId?: true
  dayStart?: true
  dayEnd?: true
}

export type ProgramItemSumAggregateInputType = {
  id?: true
  programId?: true
  asceticismId?: true
  dayStart?: true
  dayEnd?: true
}

export type ProgramItemMinAggregateInputType = {
  id?: true
  programId?: true
  asceticismId?: true
  dayStart?: true
  dayEnd?: true
}

export type ProgramItemMaxAggregateInputType = {
  id?: true
  programId?: true
  asceticismId?: true
  dayStart?: true
  dayEnd?: true
}

export type ProgramItemCountAggregateInputType = {
  id?: true
  programId?: true
  asceticismId?: true
  dayStart?: true
  dayEnd?: true
  metadata?: true
  _all?: true
}

export type ProgramItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramItem to aggregate.
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramItems to fetch.
   */
  orderBy?: Prisma.ProgramItemOrderByWithRelationInput | Prisma.ProgramItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProgramItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProgramItems
  **/
  _count?: true | ProgramItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProgramItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProgramItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProgramItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProgramItemMaxAggregateInputType
}

export type GetProgramItemAggregateType<T extends ProgramItemAggregateArgs> = {
      [P in keyof T & keyof AggregateProgramItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProgramItem[P]>
    : Prisma.GetScalarType<T[P], AggregateProgramItem[P]>
}




export type ProgramItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgramItemWhereInput
  orderBy?: Prisma.ProgramItemOrderByWithAggregationInput | Prisma.ProgramItemOrderByWithAggregationInput[]
  by: Prisma.ProgramItemScalarFieldEnum[] | Prisma.ProgramItemScalarFieldEnum
  having?: Prisma.ProgramItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProgramItemCountAggregateInputType | true
  _avg?: ProgramItemAvgAggregateInputType
  _sum?: ProgramItemSumAggregateInputType
  _min?: ProgramItemMinAggregateInputType
  _max?: ProgramItemMaxAggregateInputType
}

export type ProgramItemGroupByOutputType = {
  id: number
  programId: number
  asceticismId: number
  dayStart: number
  dayEnd: number | null
  metadata: runtime.JsonValue | null
  _count: ProgramItemCountAggregateOutputType | null
  _avg: ProgramItemAvgAggregateOutputType | null
  _sum: ProgramItemSumAggregateOutputType | null
  _min: ProgramItemMinAggregateOutputType | null
  _max: ProgramItemMaxAggregateOutputType | null
}

type GetProgramItemGroupByPayload<T extends ProgramItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProgramItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProgramItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProgramItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProgramItemGroupByOutputType[P]>
      }
    >
  >



export type ProgramItemWhereInput = {
  AND?: Prisma.ProgramItemWhereInput | Prisma.ProgramItemWhereInput[]
  OR?: Prisma.ProgramItemWhereInput[]
  NOT?: Prisma.ProgramItemWhereInput | Prisma.ProgramItemWhereInput[]
  id?: Prisma.IntFilter<"ProgramItem"> | number
  programId?: Prisma.IntFilter<"ProgramItem"> | number
  asceticismId?: Prisma.IntFilter<"ProgramItem"> | number
  dayStart?: Prisma.IntFilter<"ProgramItem"> | number
  dayEnd?: Prisma.IntNullableFilter<"ProgramItem"> | number | null
  metadata?: Prisma.JsonNullableFilter<"ProgramItem">
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
  asceticism?: Prisma.XOR<Prisma.AsceticismScalarRelationFilter, Prisma.AsceticismWhereInput>
}

export type ProgramItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  program?: Prisma.ProgramOrderByWithRelationInput
  asceticism?: Prisma.AsceticismOrderByWithRelationInput
}

export type ProgramItemWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ProgramItemWhereInput | Prisma.ProgramItemWhereInput[]
  OR?: Prisma.ProgramItemWhereInput[]
  NOT?: Prisma.ProgramItemWhereInput | Prisma.ProgramItemWhereInput[]
  programId?: Prisma.IntFilter<"ProgramItem"> | number
  asceticismId?: Prisma.IntFilter<"ProgramItem"> | number
  dayStart?: Prisma.IntFilter<"ProgramItem"> | number
  dayEnd?: Prisma.IntNullableFilter<"ProgramItem"> | number | null
  metadata?: Prisma.JsonNullableFilter<"ProgramItem">
  program?: Prisma.XOR<Prisma.ProgramScalarRelationFilter, Prisma.ProgramWhereInput>
  asceticism?: Prisma.XOR<Prisma.AsceticismScalarRelationFilter, Prisma.AsceticismWhereInput>
}, "id">

export type ProgramItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProgramItemCountOrderByAggregateInput
  _avg?: Prisma.ProgramItemAvgOrderByAggregateInput
  _max?: Prisma.ProgramItemMaxOrderByAggregateInput
  _min?: Prisma.ProgramItemMinOrderByAggregateInput
  _sum?: Prisma.ProgramItemSumOrderByAggregateInput
}

export type ProgramItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProgramItemScalarWhereWithAggregatesInput | Prisma.ProgramItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProgramItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProgramItemScalarWhereWithAggregatesInput | Prisma.ProgramItemScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ProgramItem"> | number
  programId?: Prisma.IntWithAggregatesFilter<"ProgramItem"> | number
  asceticismId?: Prisma.IntWithAggregatesFilter<"ProgramItem"> | number
  dayStart?: Prisma.IntWithAggregatesFilter<"ProgramItem"> | number
  dayEnd?: Prisma.IntNullableWithAggregatesFilter<"ProgramItem"> | number | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"ProgramItem">
}

export type ProgramItemCreateInput = {
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  program: Prisma.ProgramCreateNestedOneWithoutItemsInput
  asceticism: Prisma.AsceticismCreateNestedOneWithoutProgramItemsInput
}

export type ProgramItemUncheckedCreateInput = {
  id?: number
  programId: number
  asceticismId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUpdateInput = {
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  program?: Prisma.ProgramUpdateOneRequiredWithoutItemsNestedInput
  asceticism?: Prisma.AsceticismUpdateOneRequiredWithoutProgramItemsNestedInput
}

export type ProgramItemUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  programId?: Prisma.IntFieldUpdateOperationsInput | number
  asceticismId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemCreateManyInput = {
  id?: number
  programId: number
  asceticismId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUpdateManyMutationInput = {
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  programId?: Prisma.IntFieldUpdateOperationsInput | number
  asceticismId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemListRelationFilter = {
  every?: Prisma.ProgramItemWhereInput
  some?: Prisma.ProgramItemWhereInput
  none?: Prisma.ProgramItemWhereInput
}

export type ProgramItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProgramItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
}

export type ProgramItemAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrder
}

export type ProgramItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrder
}

export type ProgramItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrder
}

export type ProgramItemSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  programId?: Prisma.SortOrder
  asceticismId?: Prisma.SortOrder
  dayStart?: Prisma.SortOrder
  dayEnd?: Prisma.SortOrder
}

export type ProgramItemCreateNestedManyWithoutAsceticismInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput> | Prisma.ProgramItemCreateWithoutAsceticismInput[] | Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput | Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput[]
  createMany?: Prisma.ProgramItemCreateManyAsceticismInputEnvelope
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
}

export type ProgramItemUncheckedCreateNestedManyWithoutAsceticismInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput> | Prisma.ProgramItemCreateWithoutAsceticismInput[] | Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput | Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput[]
  createMany?: Prisma.ProgramItemCreateManyAsceticismInputEnvelope
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
}

export type ProgramItemUpdateManyWithoutAsceticismNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput> | Prisma.ProgramItemCreateWithoutAsceticismInput[] | Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput | Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput[]
  upsert?: Prisma.ProgramItemUpsertWithWhereUniqueWithoutAsceticismInput | Prisma.ProgramItemUpsertWithWhereUniqueWithoutAsceticismInput[]
  createMany?: Prisma.ProgramItemCreateManyAsceticismInputEnvelope
  set?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  disconnect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  delete?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  update?: Prisma.ProgramItemUpdateWithWhereUniqueWithoutAsceticismInput | Prisma.ProgramItemUpdateWithWhereUniqueWithoutAsceticismInput[]
  updateMany?: Prisma.ProgramItemUpdateManyWithWhereWithoutAsceticismInput | Prisma.ProgramItemUpdateManyWithWhereWithoutAsceticismInput[]
  deleteMany?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
}

export type ProgramItemUncheckedUpdateManyWithoutAsceticismNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput> | Prisma.ProgramItemCreateWithoutAsceticismInput[] | Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput | Prisma.ProgramItemCreateOrConnectWithoutAsceticismInput[]
  upsert?: Prisma.ProgramItemUpsertWithWhereUniqueWithoutAsceticismInput | Prisma.ProgramItemUpsertWithWhereUniqueWithoutAsceticismInput[]
  createMany?: Prisma.ProgramItemCreateManyAsceticismInputEnvelope
  set?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  disconnect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  delete?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  update?: Prisma.ProgramItemUpdateWithWhereUniqueWithoutAsceticismInput | Prisma.ProgramItemUpdateWithWhereUniqueWithoutAsceticismInput[]
  updateMany?: Prisma.ProgramItemUpdateManyWithWhereWithoutAsceticismInput | Prisma.ProgramItemUpdateManyWithWhereWithoutAsceticismInput[]
  deleteMany?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
}

export type ProgramItemCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput> | Prisma.ProgramItemCreateWithoutProgramInput[] | Prisma.ProgramItemUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutProgramInput | Prisma.ProgramItemCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.ProgramItemCreateManyProgramInputEnvelope
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
}

export type ProgramItemUncheckedCreateNestedManyWithoutProgramInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput> | Prisma.ProgramItemCreateWithoutProgramInput[] | Prisma.ProgramItemUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutProgramInput | Prisma.ProgramItemCreateOrConnectWithoutProgramInput[]
  createMany?: Prisma.ProgramItemCreateManyProgramInputEnvelope
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
}

export type ProgramItemUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput> | Prisma.ProgramItemCreateWithoutProgramInput[] | Prisma.ProgramItemUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutProgramInput | Prisma.ProgramItemCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.ProgramItemUpsertWithWhereUniqueWithoutProgramInput | Prisma.ProgramItemUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.ProgramItemCreateManyProgramInputEnvelope
  set?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  disconnect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  delete?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  update?: Prisma.ProgramItemUpdateWithWhereUniqueWithoutProgramInput | Prisma.ProgramItemUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.ProgramItemUpdateManyWithWhereWithoutProgramInput | Prisma.ProgramItemUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
}

export type ProgramItemUncheckedUpdateManyWithoutProgramNestedInput = {
  create?: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput> | Prisma.ProgramItemCreateWithoutProgramInput[] | Prisma.ProgramItemUncheckedCreateWithoutProgramInput[]
  connectOrCreate?: Prisma.ProgramItemCreateOrConnectWithoutProgramInput | Prisma.ProgramItemCreateOrConnectWithoutProgramInput[]
  upsert?: Prisma.ProgramItemUpsertWithWhereUniqueWithoutProgramInput | Prisma.ProgramItemUpsertWithWhereUniqueWithoutProgramInput[]
  createMany?: Prisma.ProgramItemCreateManyProgramInputEnvelope
  set?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  disconnect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  delete?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  connect?: Prisma.ProgramItemWhereUniqueInput | Prisma.ProgramItemWhereUniqueInput[]
  update?: Prisma.ProgramItemUpdateWithWhereUniqueWithoutProgramInput | Prisma.ProgramItemUpdateWithWhereUniqueWithoutProgramInput[]
  updateMany?: Prisma.ProgramItemUpdateManyWithWhereWithoutProgramInput | Prisma.ProgramItemUpdateManyWithWhereWithoutProgramInput[]
  deleteMany?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
}

export type ProgramItemCreateWithoutAsceticismInput = {
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  program: Prisma.ProgramCreateNestedOneWithoutItemsInput
}

export type ProgramItemUncheckedCreateWithoutAsceticismInput = {
  id?: number
  programId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemCreateOrConnectWithoutAsceticismInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput>
}

export type ProgramItemCreateManyAsceticismInputEnvelope = {
  data: Prisma.ProgramItemCreateManyAsceticismInput | Prisma.ProgramItemCreateManyAsceticismInput[]
  skipDuplicates?: boolean
}

export type ProgramItemUpsertWithWhereUniqueWithoutAsceticismInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ProgramItemUpdateWithoutAsceticismInput, Prisma.ProgramItemUncheckedUpdateWithoutAsceticismInput>
  create: Prisma.XOR<Prisma.ProgramItemCreateWithoutAsceticismInput, Prisma.ProgramItemUncheckedCreateWithoutAsceticismInput>
}

export type ProgramItemUpdateWithWhereUniqueWithoutAsceticismInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ProgramItemUpdateWithoutAsceticismInput, Prisma.ProgramItemUncheckedUpdateWithoutAsceticismInput>
}

export type ProgramItemUpdateManyWithWhereWithoutAsceticismInput = {
  where: Prisma.ProgramItemScalarWhereInput
  data: Prisma.XOR<Prisma.ProgramItemUpdateManyMutationInput, Prisma.ProgramItemUncheckedUpdateManyWithoutAsceticismInput>
}

export type ProgramItemScalarWhereInput = {
  AND?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
  OR?: Prisma.ProgramItemScalarWhereInput[]
  NOT?: Prisma.ProgramItemScalarWhereInput | Prisma.ProgramItemScalarWhereInput[]
  id?: Prisma.IntFilter<"ProgramItem"> | number
  programId?: Prisma.IntFilter<"ProgramItem"> | number
  asceticismId?: Prisma.IntFilter<"ProgramItem"> | number
  dayStart?: Prisma.IntFilter<"ProgramItem"> | number
  dayEnd?: Prisma.IntNullableFilter<"ProgramItem"> | number | null
  metadata?: Prisma.JsonNullableFilter<"ProgramItem">
}

export type ProgramItemCreateWithoutProgramInput = {
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  asceticism: Prisma.AsceticismCreateNestedOneWithoutProgramItemsInput
}

export type ProgramItemUncheckedCreateWithoutProgramInput = {
  id?: number
  asceticismId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemCreateOrConnectWithoutProgramInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput>
}

export type ProgramItemCreateManyProgramInputEnvelope = {
  data: Prisma.ProgramItemCreateManyProgramInput | Prisma.ProgramItemCreateManyProgramInput[]
  skipDuplicates?: boolean
}

export type ProgramItemUpsertWithWhereUniqueWithoutProgramInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  update: Prisma.XOR<Prisma.ProgramItemUpdateWithoutProgramInput, Prisma.ProgramItemUncheckedUpdateWithoutProgramInput>
  create: Prisma.XOR<Prisma.ProgramItemCreateWithoutProgramInput, Prisma.ProgramItemUncheckedCreateWithoutProgramInput>
}

export type ProgramItemUpdateWithWhereUniqueWithoutProgramInput = {
  where: Prisma.ProgramItemWhereUniqueInput
  data: Prisma.XOR<Prisma.ProgramItemUpdateWithoutProgramInput, Prisma.ProgramItemUncheckedUpdateWithoutProgramInput>
}

export type ProgramItemUpdateManyWithWhereWithoutProgramInput = {
  where: Prisma.ProgramItemScalarWhereInput
  data: Prisma.XOR<Prisma.ProgramItemUpdateManyMutationInput, Prisma.ProgramItemUncheckedUpdateManyWithoutProgramInput>
}

export type ProgramItemCreateManyAsceticismInput = {
  id?: number
  programId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUpdateWithoutAsceticismInput = {
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  program?: Prisma.ProgramUpdateOneRequiredWithoutItemsNestedInput
}

export type ProgramItemUncheckedUpdateWithoutAsceticismInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  programId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUncheckedUpdateManyWithoutAsceticismInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  programId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemCreateManyProgramInput = {
  id?: number
  asceticismId: number
  dayStart?: number
  dayEnd?: number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUpdateWithoutProgramInput = {
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  asceticism?: Prisma.AsceticismUpdateOneRequiredWithoutProgramItemsNestedInput
}

export type ProgramItemUncheckedUpdateWithoutProgramInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  asceticismId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}

export type ProgramItemUncheckedUpdateManyWithoutProgramInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  asceticismId?: Prisma.IntFieldUpdateOperationsInput | number
  dayStart?: Prisma.IntFieldUpdateOperationsInput | number
  dayEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
}



export type ProgramItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  asceticismId?: boolean
  dayStart?: boolean
  dayEnd?: boolean
  metadata?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programItem"]>

export type ProgramItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  asceticismId?: boolean
  dayStart?: boolean
  dayEnd?: boolean
  metadata?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programItem"]>

export type ProgramItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  programId?: boolean
  asceticismId?: boolean
  dayStart?: boolean
  dayEnd?: boolean
  metadata?: boolean
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}, ExtArgs["result"]["programItem"]>

export type ProgramItemSelectScalar = {
  id?: boolean
  programId?: boolean
  asceticismId?: boolean
  dayStart?: boolean
  dayEnd?: boolean
  metadata?: boolean
}

export type ProgramItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "programId" | "asceticismId" | "dayStart" | "dayEnd" | "metadata", ExtArgs["result"]["programItem"]>
export type ProgramItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}
export type ProgramItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}
export type ProgramItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  program?: boolean | Prisma.ProgramDefaultArgs<ExtArgs>
  asceticism?: boolean | Prisma.AsceticismDefaultArgs<ExtArgs>
}

export type $ProgramItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProgramItem"
  objects: {
    program: Prisma.$ProgramPayload<ExtArgs>
    asceticism: Prisma.$AsceticismPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    programId: number
    asceticismId: number
    dayStart: number
    dayEnd: number | null
    metadata: runtime.JsonValue | null
  }, ExtArgs["result"]["programItem"]>
  composites: {}
}

export type ProgramItemGetPayload<S extends boolean | null | undefined | ProgramItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload, S>

export type ProgramItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProgramItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProgramItemCountAggregateInputType | true
  }

export interface ProgramItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProgramItem'], meta: { name: 'ProgramItem' } }
  /**
   * Find zero or one ProgramItem that matches the filter.
   * @param {ProgramItemFindUniqueArgs} args - Arguments to find a ProgramItem
   * @example
   * // Get one ProgramItem
   * const programItem = await prisma.programItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProgramItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ProgramItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProgramItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProgramItemFindUniqueOrThrowArgs} args - Arguments to find a ProgramItem
   * @example
   * // Get one ProgramItem
   * const programItem = await prisma.programItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProgramItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProgramItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemFindFirstArgs} args - Arguments to find a ProgramItem
   * @example
   * // Get one ProgramItem
   * const programItem = await prisma.programItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProgramItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ProgramItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProgramItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemFindFirstOrThrowArgs} args - Arguments to find a ProgramItem
   * @example
   * // Get one ProgramItem
   * const programItem = await prisma.programItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProgramItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProgramItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProgramItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProgramItems
   * const programItems = await prisma.programItem.findMany()
   * 
   * // Get first 10 ProgramItems
   * const programItems = await prisma.programItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const programItemWithIdOnly = await prisma.programItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProgramItemFindManyArgs>(args?: Prisma.SelectSubset<T, ProgramItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProgramItem.
   * @param {ProgramItemCreateArgs} args - Arguments to create a ProgramItem.
   * @example
   * // Create one ProgramItem
   * const ProgramItem = await prisma.programItem.create({
   *   data: {
   *     // ... data to create a ProgramItem
   *   }
   * })
   * 
   */
  create<T extends ProgramItemCreateArgs>(args: Prisma.SelectSubset<T, ProgramItemCreateArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProgramItems.
   * @param {ProgramItemCreateManyArgs} args - Arguments to create many ProgramItems.
   * @example
   * // Create many ProgramItems
   * const programItem = await prisma.programItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProgramItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ProgramItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProgramItems and returns the data saved in the database.
   * @param {ProgramItemCreateManyAndReturnArgs} args - Arguments to create many ProgramItems.
   * @example
   * // Create many ProgramItems
   * const programItem = await prisma.programItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProgramItems and only return the `id`
   * const programItemWithIdOnly = await prisma.programItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProgramItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProgramItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProgramItem.
   * @param {ProgramItemDeleteArgs} args - Arguments to delete one ProgramItem.
   * @example
   * // Delete one ProgramItem
   * const ProgramItem = await prisma.programItem.delete({
   *   where: {
   *     // ... filter to delete one ProgramItem
   *   }
   * })
   * 
   */
  delete<T extends ProgramItemDeleteArgs>(args: Prisma.SelectSubset<T, ProgramItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProgramItem.
   * @param {ProgramItemUpdateArgs} args - Arguments to update one ProgramItem.
   * @example
   * // Update one ProgramItem
   * const programItem = await prisma.programItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProgramItemUpdateArgs>(args: Prisma.SelectSubset<T, ProgramItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProgramItems.
   * @param {ProgramItemDeleteManyArgs} args - Arguments to filter ProgramItems to delete.
   * @example
   * // Delete a few ProgramItems
   * const { count } = await prisma.programItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProgramItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProgramItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProgramItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProgramItems
   * const programItem = await prisma.programItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProgramItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ProgramItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProgramItems and returns the data updated in the database.
   * @param {ProgramItemUpdateManyAndReturnArgs} args - Arguments to update many ProgramItems.
   * @example
   * // Update many ProgramItems
   * const programItem = await prisma.programItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProgramItems and only return the `id`
   * const programItemWithIdOnly = await prisma.programItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProgramItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProgramItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProgramItem.
   * @param {ProgramItemUpsertArgs} args - Arguments to update or create a ProgramItem.
   * @example
   * // Update or create a ProgramItem
   * const programItem = await prisma.programItem.upsert({
   *   create: {
   *     // ... data to create a ProgramItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProgramItem we want to update
   *   }
   * })
   */
  upsert<T extends ProgramItemUpsertArgs>(args: Prisma.SelectSubset<T, ProgramItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ProgramItemClient<runtime.Types.Result.GetResult<Prisma.$ProgramItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProgramItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemCountArgs} args - Arguments to filter ProgramItems to count.
   * @example
   * // Count the number of ProgramItems
   * const count = await prisma.programItem.count({
   *   where: {
   *     // ... the filter for the ProgramItems we want to count
   *   }
   * })
  **/
  count<T extends ProgramItemCountArgs>(
    args?: Prisma.Subset<T, ProgramItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProgramItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProgramItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProgramItemAggregateArgs>(args: Prisma.Subset<T, ProgramItemAggregateArgs>): Prisma.PrismaPromise<GetProgramItemAggregateType<T>>

  /**
   * Group by ProgramItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgramItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProgramItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProgramItemGroupByArgs['orderBy'] }
      : { orderBy?: ProgramItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProgramItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProgramItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProgramItem model
 */
readonly fields: ProgramItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProgramItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProgramItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  program<T extends Prisma.ProgramDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgramDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgramClient<runtime.Types.Result.GetResult<Prisma.$ProgramPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  asceticism<T extends Prisma.AsceticismDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AsceticismDefaultArgs<ExtArgs>>): Prisma.Prisma__AsceticismClient<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProgramItem model
 */
export interface ProgramItemFieldRefs {
  readonly id: Prisma.FieldRef<"ProgramItem", 'Int'>
  readonly programId: Prisma.FieldRef<"ProgramItem", 'Int'>
  readonly asceticismId: Prisma.FieldRef<"ProgramItem", 'Int'>
  readonly dayStart: Prisma.FieldRef<"ProgramItem", 'Int'>
  readonly dayEnd: Prisma.FieldRef<"ProgramItem", 'Int'>
  readonly metadata: Prisma.FieldRef<"ProgramItem", 'Json'>
}
    

// Custom InputTypes
/**
 * ProgramItem findUnique
 */
export type ProgramItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter, which ProgramItem to fetch.
   */
  where: Prisma.ProgramItemWhereUniqueInput
}

/**
 * ProgramItem findUniqueOrThrow
 */
export type ProgramItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter, which ProgramItem to fetch.
   */
  where: Prisma.ProgramItemWhereUniqueInput
}

/**
 * ProgramItem findFirst
 */
export type ProgramItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter, which ProgramItem to fetch.
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramItems to fetch.
   */
  orderBy?: Prisma.ProgramItemOrderByWithRelationInput | Prisma.ProgramItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramItems.
   */
  cursor?: Prisma.ProgramItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramItems.
   */
  distinct?: Prisma.ProgramItemScalarFieldEnum | Prisma.ProgramItemScalarFieldEnum[]
}

/**
 * ProgramItem findFirstOrThrow
 */
export type ProgramItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter, which ProgramItem to fetch.
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramItems to fetch.
   */
  orderBy?: Prisma.ProgramItemOrderByWithRelationInput | Prisma.ProgramItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProgramItems.
   */
  cursor?: Prisma.ProgramItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProgramItems.
   */
  distinct?: Prisma.ProgramItemScalarFieldEnum | Prisma.ProgramItemScalarFieldEnum[]
}

/**
 * ProgramItem findMany
 */
export type ProgramItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter, which ProgramItems to fetch.
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProgramItems to fetch.
   */
  orderBy?: Prisma.ProgramItemOrderByWithRelationInput | Prisma.ProgramItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProgramItems.
   */
  cursor?: Prisma.ProgramItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProgramItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProgramItems.
   */
  skip?: number
  distinct?: Prisma.ProgramItemScalarFieldEnum | Prisma.ProgramItemScalarFieldEnum[]
}

/**
 * ProgramItem create
 */
export type ProgramItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * The data needed to create a ProgramItem.
   */
  data: Prisma.XOR<Prisma.ProgramItemCreateInput, Prisma.ProgramItemUncheckedCreateInput>
}

/**
 * ProgramItem createMany
 */
export type ProgramItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProgramItems.
   */
  data: Prisma.ProgramItemCreateManyInput | Prisma.ProgramItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProgramItem createManyAndReturn
 */
export type ProgramItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * The data used to create many ProgramItems.
   */
  data: Prisma.ProgramItemCreateManyInput | Prisma.ProgramItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProgramItem update
 */
export type ProgramItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * The data needed to update a ProgramItem.
   */
  data: Prisma.XOR<Prisma.ProgramItemUpdateInput, Prisma.ProgramItemUncheckedUpdateInput>
  /**
   * Choose, which ProgramItem to update.
   */
  where: Prisma.ProgramItemWhereUniqueInput
}

/**
 * ProgramItem updateMany
 */
export type ProgramItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProgramItems.
   */
  data: Prisma.XOR<Prisma.ProgramItemUpdateManyMutationInput, Prisma.ProgramItemUncheckedUpdateManyInput>
  /**
   * Filter which ProgramItems to update
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * Limit how many ProgramItems to update.
   */
  limit?: number
}

/**
 * ProgramItem updateManyAndReturn
 */
export type ProgramItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * The data used to update ProgramItems.
   */
  data: Prisma.XOR<Prisma.ProgramItemUpdateManyMutationInput, Prisma.ProgramItemUncheckedUpdateManyInput>
  /**
   * Filter which ProgramItems to update
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * Limit how many ProgramItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProgramItem upsert
 */
export type ProgramItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * The filter to search for the ProgramItem to update in case it exists.
   */
  where: Prisma.ProgramItemWhereUniqueInput
  /**
   * In case the ProgramItem found by the `where` argument doesn't exist, create a new ProgramItem with this data.
   */
  create: Prisma.XOR<Prisma.ProgramItemCreateInput, Prisma.ProgramItemUncheckedCreateInput>
  /**
   * In case the ProgramItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProgramItemUpdateInput, Prisma.ProgramItemUncheckedUpdateInput>
}

/**
 * ProgramItem delete
 */
export type ProgramItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
  /**
   * Filter which ProgramItem to delete.
   */
  where: Prisma.ProgramItemWhereUniqueInput
}

/**
 * ProgramItem deleteMany
 */
export type ProgramItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProgramItems to delete
   */
  where?: Prisma.ProgramItemWhereInput
  /**
   * Limit how many ProgramItems to delete.
   */
  limit?: number
}

/**
 * ProgramItem without action
 */
export type ProgramItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgramItem
   */
  select?: Prisma.ProgramItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProgramItem
   */
  omit?: Prisma.ProgramItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgramItemInclude<ExtArgs> | null
}
