
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserAvgAggregateOutputType = {
  id: number | null
}

export type UserSumAggregateOutputType = {
  id: number | null
}

export type UserMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  emailVerified: Date | null
  image: string | null
  role: $Enums.UserRole | null
  isBanned: boolean | null
}

export type UserMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
  emailVerified: Date | null
  image: string | null
  role: $Enums.UserRole | null
  isBanned: boolean | null
}

export type UserCountAggregateOutputType = {
  id: number
  name: number
  email: number
  emailVerified: number
  image: number
  role: number
  isBanned: number
  _all: number
}


export type UserAvgAggregateInputType = {
  id?: true
}

export type UserSumAggregateInputType = {
  id?: true
}

export type UserMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  emailVerified?: true
  image?: true
  role?: true
  isBanned?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  emailVerified?: true
  image?: true
  role?: true
  isBanned?: true
}

export type UserCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  emailVerified?: true
  image?: true
  role?: true
  isBanned?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _avg?: UserAvgAggregateInputType
  _sum?: UserSumAggregateInputType
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: number
  name: string | null
  email: string | null
  emailVerified: Date | null
  image: string | null
  role: $Enums.UserRole
  isBanned: boolean
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.IntFilter<"User"> | number
  name?: Prisma.StringNullableFilter<"User"> | string | null
  email?: Prisma.StringNullableFilter<"User"> | string | null
  emailVerified?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  image?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleFilter<"User"> | $Enums.UserRole
  isBanned?: Prisma.BoolFilter<"User"> | boolean
  accounts?: Prisma.AccountListRelationFilter
  sessions?: Prisma.SessionListRelationFilter
  createdAsceticisms?: Prisma.AsceticismListRelationFilter
  userAsceticisms?: Prisma.UserAsceticismListRelationFilter
  userPrograms?: Prisma.UserProgramListRelationFilter
  groupMembers?: Prisma.GroupMemberListRelationFilter
  dailyReadingNotes?: Prisma.DailyReadingNoteListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  emailVerified?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  accounts?: Prisma.AccountOrderByRelationAggregateInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
  createdAsceticisms?: Prisma.AsceticismOrderByRelationAggregateInput
  userAsceticisms?: Prisma.UserAsceticismOrderByRelationAggregateInput
  userPrograms?: Prisma.UserProgramOrderByRelationAggregateInput
  groupMembers?: Prisma.GroupMemberOrderByRelationAggregateInput
  dailyReadingNotes?: Prisma.DailyReadingNoteOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  name?: Prisma.StringNullableFilter<"User"> | string | null
  emailVerified?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null
  image?: Prisma.StringNullableFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleFilter<"User"> | $Enums.UserRole
  isBanned?: Prisma.BoolFilter<"User"> | boolean
  accounts?: Prisma.AccountListRelationFilter
  sessions?: Prisma.SessionListRelationFilter
  createdAsceticisms?: Prisma.AsceticismListRelationFilter
  userAsceticisms?: Prisma.UserAsceticismListRelationFilter
  userPrograms?: Prisma.UserProgramListRelationFilter
  groupMembers?: Prisma.GroupMemberListRelationFilter
  dailyReadingNotes?: Prisma.DailyReadingNoteListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  emailVerified?: Prisma.SortOrderInput | Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _avg?: Prisma.UserAvgOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
  _sum?: Prisma.UserSumOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"User"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  emailVerified?: Prisma.DateTimeNullableWithAggregatesFilter<"User"> | Date | string | null
  image?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  role?: Prisma.EnumUserRoleWithAggregatesFilter<"User"> | $Enums.UserRole
  isBanned?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
}

export type UserCreateInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
}

export type UserUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  emailVerified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
}

export type UserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  emailVerified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  emailVerified?: Prisma.SortOrder
  image?: Prisma.SortOrder
  role?: Prisma.SortOrder
  isBanned?: Prisma.SortOrder
}

export type UserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type UserCreateNestedOneWithoutAccountsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAccountsInput, Prisma.UserUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAccountsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutAccountsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAccountsInput, Prisma.UserUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAccountsInput
  upsert?: Prisma.UserUpsertWithoutAccountsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAccountsInput, Prisma.UserUpdateWithoutAccountsInput>, Prisma.UserUncheckedUpdateWithoutAccountsInput>
}

export type UserCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSessionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.UserUpsertWithoutSessionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSessionsInput, Prisma.UserUpdateWithoutSessionsInput>, Prisma.UserUncheckedUpdateWithoutSessionsInput>
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumUserRoleFieldUpdateOperationsInput = {
  set?: $Enums.UserRole
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type UserCreateNestedOneWithoutCreatedAsceticismsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedCreateWithoutCreatedAsceticismsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedAsceticismsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutCreatedAsceticismsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedCreateWithoutCreatedAsceticismsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCreatedAsceticismsInput
  upsert?: Prisma.UserUpsertWithoutCreatedAsceticismsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCreatedAsceticismsInput, Prisma.UserUpdateWithoutCreatedAsceticismsInput>, Prisma.UserUncheckedUpdateWithoutCreatedAsceticismsInput>
}

export type UserCreateNestedOneWithoutUserAsceticismsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserAsceticismsInput, Prisma.UserUncheckedCreateWithoutUserAsceticismsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserAsceticismsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutUserAsceticismsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserAsceticismsInput, Prisma.UserUncheckedCreateWithoutUserAsceticismsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserAsceticismsInput
  upsert?: Prisma.UserUpsertWithoutUserAsceticismsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutUserAsceticismsInput, Prisma.UserUpdateWithoutUserAsceticismsInput>, Prisma.UserUncheckedUpdateWithoutUserAsceticismsInput>
}

export type UserCreateNestedOneWithoutUserProgramsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserProgramsInput, Prisma.UserUncheckedCreateWithoutUserProgramsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserProgramsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutUserProgramsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserProgramsInput, Prisma.UserUncheckedCreateWithoutUserProgramsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserProgramsInput
  upsert?: Prisma.UserUpsertWithoutUserProgramsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutUserProgramsInput, Prisma.UserUpdateWithoutUserProgramsInput>, Prisma.UserUncheckedUpdateWithoutUserProgramsInput>
}

export type UserCreateNestedOneWithoutGroupMembersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutGroupMembersInput, Prisma.UserUncheckedCreateWithoutGroupMembersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutGroupMembersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutGroupMembersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutGroupMembersInput, Prisma.UserUncheckedCreateWithoutGroupMembersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutGroupMembersInput
  upsert?: Prisma.UserUpsertWithoutGroupMembersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutGroupMembersInput, Prisma.UserUpdateWithoutGroupMembersInput>, Prisma.UserUncheckedUpdateWithoutGroupMembersInput>
}

export type UserCreateNestedOneWithoutDailyReadingNotesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDailyReadingNotesInput, Prisma.UserUncheckedCreateWithoutDailyReadingNotesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDailyReadingNotesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutDailyReadingNotesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutDailyReadingNotesInput, Prisma.UserUncheckedCreateWithoutDailyReadingNotesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutDailyReadingNotesInput
  upsert?: Prisma.UserUpsertWithoutDailyReadingNotesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutDailyReadingNotesInput, Prisma.UserUpdateWithoutDailyReadingNotesInput>, Prisma.UserUncheckedUpdateWithoutDailyReadingNotesInput>
}

export type UserCreateWithoutAccountsInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutAccountsInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutAccountsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAccountsInput, Prisma.UserUncheckedCreateWithoutAccountsInput>
}

export type UserUpsertWithoutAccountsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAccountsInput, Prisma.UserUncheckedUpdateWithoutAccountsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAccountsInput, Prisma.UserUncheckedCreateWithoutAccountsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAccountsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAccountsInput, Prisma.UserUncheckedUpdateWithoutAccountsInput>
}

export type UserUpdateWithoutAccountsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutAccountsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutSessionsInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutSessionsInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutSessionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
}

export type UserUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSessionsInput, Prisma.UserUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSessionsInput, Prisma.UserUncheckedCreateWithoutSessionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSessionsInput, Prisma.UserUncheckedUpdateWithoutSessionsInput>
}

export type UserUpdateWithoutSessionsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCreatedAsceticismsInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCreatedAsceticismsInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCreatedAsceticismsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedCreateWithoutCreatedAsceticismsInput>
}

export type UserUpsertWithoutCreatedAsceticismsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedUpdateWithoutCreatedAsceticismsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedCreateWithoutCreatedAsceticismsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCreatedAsceticismsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCreatedAsceticismsInput, Prisma.UserUncheckedUpdateWithoutCreatedAsceticismsInput>
}

export type UserUpdateWithoutCreatedAsceticismsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCreatedAsceticismsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutUserAsceticismsInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutUserAsceticismsInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutUserAsceticismsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutUserAsceticismsInput, Prisma.UserUncheckedCreateWithoutUserAsceticismsInput>
}

export type UserUpsertWithoutUserAsceticismsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutUserAsceticismsInput, Prisma.UserUncheckedUpdateWithoutUserAsceticismsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutUserAsceticismsInput, Prisma.UserUncheckedCreateWithoutUserAsceticismsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutUserAsceticismsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutUserAsceticismsInput, Prisma.UserUncheckedUpdateWithoutUserAsceticismsInput>
}

export type UserUpdateWithoutUserAsceticismsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutUserAsceticismsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutUserProgramsInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutUserProgramsInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutUserProgramsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutUserProgramsInput, Prisma.UserUncheckedCreateWithoutUserProgramsInput>
}

export type UserUpsertWithoutUserProgramsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutUserProgramsInput, Prisma.UserUncheckedUpdateWithoutUserProgramsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutUserProgramsInput, Prisma.UserUncheckedCreateWithoutUserProgramsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutUserProgramsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutUserProgramsInput, Prisma.UserUncheckedUpdateWithoutUserProgramsInput>
}

export type UserUpdateWithoutUserProgramsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutUserProgramsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutGroupMembersInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutGroupMembersInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutGroupMembersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutGroupMembersInput, Prisma.UserUncheckedCreateWithoutGroupMembersInput>
}

export type UserUpsertWithoutGroupMembersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutGroupMembersInput, Prisma.UserUncheckedUpdateWithoutGroupMembersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutGroupMembersInput, Prisma.UserUncheckedCreateWithoutGroupMembersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutGroupMembersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutGroupMembersInput, Prisma.UserUncheckedUpdateWithoutGroupMembersInput>
}

export type UserUpdateWithoutGroupMembersInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutGroupMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  dailyReadingNotes?: Prisma.DailyReadingNoteUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutDailyReadingNotesInput = {
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutDailyReadingNotesInput = {
  id?: number
  name?: string | null
  email?: string | null
  emailVerified?: Date | string | null
  image?: string | null
  role?: $Enums.UserRole
  isBanned?: boolean
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutUserInput
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutUserInput
  createdAsceticisms?: Prisma.AsceticismUncheckedCreateNestedManyWithoutCreatorInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedCreateNestedManyWithoutUserInput
  userPrograms?: Prisma.UserProgramUncheckedCreateNestedManyWithoutUserInput
  groupMembers?: Prisma.GroupMemberUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutDailyReadingNotesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutDailyReadingNotesInput, Prisma.UserUncheckedCreateWithoutDailyReadingNotesInput>
}

export type UserUpsertWithoutDailyReadingNotesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutDailyReadingNotesInput, Prisma.UserUncheckedUpdateWithoutDailyReadingNotesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutDailyReadingNotesInput, Prisma.UserUncheckedCreateWithoutDailyReadingNotesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutDailyReadingNotesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutDailyReadingNotesInput, Prisma.UserUncheckedUpdateWithoutDailyReadingNotesInput>
}

export type UserUpdateWithoutDailyReadingNotesInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutDailyReadingNotesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emailVerified?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.EnumUserRoleFieldUpdateOperationsInput | $Enums.UserRole
  isBanned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutUserNestedInput
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutUserNestedInput
  createdAsceticisms?: Prisma.AsceticismUncheckedUpdateManyWithoutCreatorNestedInput
  userAsceticisms?: Prisma.UserAsceticismUncheckedUpdateManyWithoutUserNestedInput
  userPrograms?: Prisma.UserProgramUncheckedUpdateManyWithoutUserNestedInput
  groupMembers?: Prisma.GroupMemberUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  accounts: number
  sessions: number
  createdAsceticisms: number
  userAsceticisms: number
  userPrograms: number
  groupMembers: number
  dailyReadingNotes: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accounts?: boolean | UserCountOutputTypeCountAccountsArgs
  sessions?: boolean | UserCountOutputTypeCountSessionsArgs
  createdAsceticisms?: boolean | UserCountOutputTypeCountCreatedAsceticismsArgs
  userAsceticisms?: boolean | UserCountOutputTypeCountUserAsceticismsArgs
  userPrograms?: boolean | UserCountOutputTypeCountUserProgramsArgs
  groupMembers?: boolean | UserCountOutputTypeCountGroupMembersArgs
  dailyReadingNotes?: boolean | UserCountOutputTypeCountDailyReadingNotesArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAccountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCreatedAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AsceticismWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountUserAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserAsceticismWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountUserProgramsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserProgramWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountGroupMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GroupMemberWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountDailyReadingNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DailyReadingNoteWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  emailVerified?: boolean
  image?: boolean
  role?: boolean
  isBanned?: boolean
  accounts?: boolean | Prisma.User$accountsArgs<ExtArgs>
  sessions?: boolean | Prisma.User$sessionsArgs<ExtArgs>
  createdAsceticisms?: boolean | Prisma.User$createdAsceticismsArgs<ExtArgs>
  userAsceticisms?: boolean | Prisma.User$userAsceticismsArgs<ExtArgs>
  userPrograms?: boolean | Prisma.User$userProgramsArgs<ExtArgs>
  groupMembers?: boolean | Prisma.User$groupMembersArgs<ExtArgs>
  dailyReadingNotes?: boolean | Prisma.User$dailyReadingNotesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  emailVerified?: boolean
  image?: boolean
  role?: boolean
  isBanned?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  emailVerified?: boolean
  image?: boolean
  role?: boolean
  isBanned?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  emailVerified?: boolean
  image?: boolean
  role?: boolean
  isBanned?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "emailVerified" | "image" | "role" | "isBanned", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accounts?: boolean | Prisma.User$accountsArgs<ExtArgs>
  sessions?: boolean | Prisma.User$sessionsArgs<ExtArgs>
  createdAsceticisms?: boolean | Prisma.User$createdAsceticismsArgs<ExtArgs>
  userAsceticisms?: boolean | Prisma.User$userAsceticismsArgs<ExtArgs>
  userPrograms?: boolean | Prisma.User$userProgramsArgs<ExtArgs>
  groupMembers?: boolean | Prisma.User$groupMembersArgs<ExtArgs>
  dailyReadingNotes?: boolean | Prisma.User$dailyReadingNotesArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    accounts: Prisma.$AccountPayload<ExtArgs>[]
    sessions: Prisma.$SessionPayload<ExtArgs>[]
    createdAsceticisms: Prisma.$AsceticismPayload<ExtArgs>[]
    userAsceticisms: Prisma.$UserAsceticismPayload<ExtArgs>[]
    userPrograms: Prisma.$UserProgramPayload<ExtArgs>[]
    groupMembers: Prisma.$GroupMemberPayload<ExtArgs>[]
    dailyReadingNotes: Prisma.$DailyReadingNotePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    email: string | null
    emailVerified: Date | null
    image: string | null
    role: $Enums.UserRole
    isBanned: boolean
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accounts<T extends Prisma.User$accountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$accountsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sessions<T extends Prisma.User$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  createdAsceticisms<T extends Prisma.User$createdAsceticismsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$createdAsceticismsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AsceticismPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userAsceticisms<T extends Prisma.User$userAsceticismsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$userAsceticismsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserAsceticismPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userPrograms<T extends Prisma.User$userProgramsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$userProgramsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserProgramPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  groupMembers<T extends Prisma.User$groupMembersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$groupMembersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GroupMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  dailyReadingNotes<T extends Prisma.User$dailyReadingNotesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$dailyReadingNotesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DailyReadingNotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'Int'>
  readonly name: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly emailVerified: Prisma.FieldRef<"User", 'DateTime'>
  readonly image: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'UserRole'>
  readonly isBanned: Prisma.FieldRef<"User", 'Boolean'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data?: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.accounts
 */
export type User$accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  where?: Prisma.AccountWhereInput
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  cursor?: Prisma.AccountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * User.sessions
 */
export type User$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * User.createdAsceticisms
 */
export type User$createdAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Asceticism
   */
  select?: Prisma.AsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Asceticism
   */
  omit?: Prisma.AsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AsceticismInclude<ExtArgs> | null
  where?: Prisma.AsceticismWhereInput
  orderBy?: Prisma.AsceticismOrderByWithRelationInput | Prisma.AsceticismOrderByWithRelationInput[]
  cursor?: Prisma.AsceticismWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AsceticismScalarFieldEnum | Prisma.AsceticismScalarFieldEnum[]
}

/**
 * User.userAsceticisms
 */
export type User$userAsceticismsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAsceticism
   */
  select?: Prisma.UserAsceticismSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAsceticism
   */
  omit?: Prisma.UserAsceticismOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserAsceticismInclude<ExtArgs> | null
  where?: Prisma.UserAsceticismWhereInput
  orderBy?: Prisma.UserAsceticismOrderByWithRelationInput | Prisma.UserAsceticismOrderByWithRelationInput[]
  cursor?: Prisma.UserAsceticismWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserAsceticismScalarFieldEnum | Prisma.UserAsceticismScalarFieldEnum[]
}

/**
 * User.userPrograms
 */
export type User$userProgramsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserProgram
   */
  select?: Prisma.UserProgramSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserProgram
   */
  omit?: Prisma.UserProgramOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserProgramInclude<ExtArgs> | null
  where?: Prisma.UserProgramWhereInput
  orderBy?: Prisma.UserProgramOrderByWithRelationInput | Prisma.UserProgramOrderByWithRelationInput[]
  cursor?: Prisma.UserProgramWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserProgramScalarFieldEnum | Prisma.UserProgramScalarFieldEnum[]
}

/**
 * User.groupMembers
 */
export type User$groupMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GroupMember
   */
  select?: Prisma.GroupMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GroupMember
   */
  omit?: Prisma.GroupMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupMemberInclude<ExtArgs> | null
  where?: Prisma.GroupMemberWhereInput
  orderBy?: Prisma.GroupMemberOrderByWithRelationInput | Prisma.GroupMemberOrderByWithRelationInput[]
  cursor?: Prisma.GroupMemberWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GroupMemberScalarFieldEnum | Prisma.GroupMemberScalarFieldEnum[]
}

/**
 * User.dailyReadingNotes
 */
export type User$dailyReadingNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DailyReadingNote
   */
  select?: Prisma.DailyReadingNoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DailyReadingNote
   */
  omit?: Prisma.DailyReadingNoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DailyReadingNoteInclude<ExtArgs> | null
  where?: Prisma.DailyReadingNoteWhereInput
  orderBy?: Prisma.DailyReadingNoteOrderByWithRelationInput | Prisma.DailyReadingNoteOrderByWithRelationInput[]
  cursor?: Prisma.DailyReadingNoteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DailyReadingNoteScalarFieldEnum | Prisma.DailyReadingNoteScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
