
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Asceticism
 * 
 */
export type Asceticism = Prisma.AsceticismModel
/**
 * Model UserAsceticism
 * 
 */
export type UserAsceticism = Prisma.UserAsceticismModel
/**
 * Model AsceticismLog
 * 
 */
export type AsceticismLog = Prisma.AsceticismLogModel
/**
 * Model AsceticismPackage
 * 
 */
export type AsceticismPackage = Prisma.AsceticismPackageModel
/**
 * Model PackageItem
 * 
 */
export type PackageItem = Prisma.PackageItemModel
/**
 * Model Program
 * 
 */
export type Program = Prisma.ProgramModel
/**
 * Model ProgramItem
 * 
 */
export type ProgramItem = Prisma.ProgramItemModel
/**
 * Model UserProgram
 * 
 */
export type UserProgram = Prisma.UserProgramModel
/**
 * Model Group
 * 
 */
export type Group = Prisma.GroupModel
/**
 * Model GroupMember
 * 
 */
export type GroupMember = Prisma.GroupMemberModel
/**
 * Model MassReading
 * 
 */
export type MassReading = Prisma.MassReadingModel
/**
 * Model DailyReadingNote
 * 
 */
export type DailyReadingNote = Prisma.DailyReadingNoteModel
