
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  USER: 'USER',
  MODERATOR: 'MODERATOR',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const TrackingType = {
  BOOLEAN: 'BOOLEAN',
  NUMERIC: 'NUMERIC',
  TEXT: 'TEXT'
} as const

export type TrackingType = (typeof TrackingType)[keyof typeof TrackingType]


export const AsceticismStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED'
} as const

export type AsceticismStatus = (typeof AsceticismStatus)[keyof typeof AsceticismStatus]


export const GroupRole = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
  MENTOR: 'MENTOR'
} as const

export type GroupRole = (typeof GroupRole)[keyof typeof GroupRole]
